### ISSUE TITLE
Placeholders should work with zip_iterator

### ISSUE THREAD

**Issue by rconnorlawson** [NVIDIA/thrust#1004]
In my code, I often have scenarios where I would like to define predicates and binary ops on tuples, for example in complicated reductions. Currently, I use functor classes where necessary. For example,

```c++
struct first_equal {
    using Tuple = thrust::tuple<int, float>;

    __device__
    const Tuple& operator()(const Tuple& t1, const Tuple& t2) {
        return thrust::get<0>(t1) == thrust::get<0>(t2);
    }
};

struct min_second {
    using Tuple = thrust::tuple<int, float>;

    __device__
    const Tuple& operator()(const Tuple& t1, const Tuple& t2) {
        return (thrust::get<1>(t1) < thrust::get<1>(t2)) ? t1 : t2;
    }
};

...

thrust::reduce(
    thrust::make_zip_iterator(thrust::make_tuple(
        input_ints.begin(), input_floats.begin())),
    thrust::make_zip_iterator(thrust::make_tuple(
        input_ints.end(), input_floats.end())),
    thrust::make_zip_iterator(thrust::make_tuple(
        output_ints.end(), output_floats.end())),
    first_equal(), min_second()
);
```

It would be nice to express these functors using placeholders. Two possible syntaxes:
```c++
get_notation:
    first_equal -> get<0>(_1) == get<0>(_2)
    min_second  -> (get<1>(_1) < get<1>(_2)) ? _1 : _2

index_notation:
    first_equal -> _1[0] == _2[0]
    min_second  -> (_1[1] < _2[1]) ? _1 : _2
```

Both of these give long template errors (missing specializations of `thrust::get`; no `operator[]` for placeholder types) when using Thrust 1.9.5 as shipped with CUDA 10.1 Update 1. As far as I can tell, there is no placeholder syntax for tuples.

**Comment by jrhemstad** [comment]
It is unlikely we will add any new functionality for `thrust::placeholders` given the fact that host/device lambdas have largely obviated the need for placeholders (though extended lambdas have their own problems).

If you believe this is still an important feature, feel free to reopen the issue.
