### ISSUE TITLE
After occurring "parallel_for failed: out of memory",it fails to call any thrust or cuda apis

### ISSUE THREAD

**Issue by ZhuShentian** [NVIDIA/thrust#1006]
i tried the code below:
`
thrust::device_vector<int> H;

try
{
H.resize(2000 * 1024 * 1024, 0);
}
catch (thrust::system_error &e)
{
std::cerr << " " << e.what() << std::endl;
}
int size_ = 1024;

thrust::device_vector<int> GH;
GH.resize(size_);
`
it threw the "parallel_for failed: out of memory" at "H.resize(2000 * 1024 * 1024, 0);"and "GH.resize(size_);",what should i suppose to do when occurring the error? i have no idea to continue using thrust or cuda api when the error occurred.

**Comment by miscco** [comment]
You cannot do anything with GH, because that vector is not even constructed due to the exception thrown during its construction.
