### ISSUE TITLE
Documentation for `par.on()` and async algorithms

### ISSUE THREAD

**Issue by brycelelbach** [NVIDIA/thrust#1013]
Yah this needs to be done.

**Comment by miscco** [comment]
async has been deprecated afaik

**Comment by pauleonix** [comment]
@miscco `par.on()` is still undocumented. Searching for it in the Jekyll docs only yields mentions in the changelogs.

**Comment by jrhemstad** [comment]
@pauleonix good point. As you can probably tell, we've been going through and cleaning out old issues. 

I've started a tracking issue to collect the various doc related issues here: https://github.com/NVIDIA/thrust/issues/1875
