### ISSUE TITLE
thrust::device_vector<T> construction always runs a kernel in the default stream

### ISSUE THREAD

**Issue by RaulPPelaez** [NVIDIA/thrust#1017]
Constructing a device_vector results in a kernel launch and a cudaDeviceSyncrhonize() down the line ( it calls one version of thrust::uninitialized_fill in thrust/detail/uninitialized_fill.inl I believe)

This seems to be dependent on an execution policy which the user has no control over (as far as I know).

What is the rationale behind this uninitialized_fill kernel launch?
Is there a way to prevent thrust from launching this kernel and calling cudaDeviceSynchronize()?
Is there a way to control the execution policy / cuda stream when constructing a device_vector?

**Comment by RaulPPelaez** [comment]
It would be cool to have something like rmm::device_uvector: https://docs.rapids.ai/api/rmm/stable/classrmm_1_1device__uvector.html
Similar to thrust::device_vector but does not default initialize its elements on construction, thus eliminating the need of a kernel launch every time.

**Comment by miscco** [comment]
For the first question:
    * We need to use the provided allocator to construct the elements and call the `construct` function. So it depends entirely what the allocator does

For the second question:
    * This is exceptionally dangerous and contradictory to the design of a container. If the elements are not initialized we cannot tell what `myvec[5]` would do. I believe we have `contiguous_storage` that acts as storage and can be used as you wish. But it would not call this a container

**Comment by jrhemstad** [comment]
fwiw, as @RaulPPelaez referenced, we have plans to add something like `rmm::device_uvector` and `thrust::contiguous_storage` to libcu++ in the nearish future.
