### ISSUE TITLE
copy_if unconditionally dereferences whole input iterator range

### ISSUE THREAD

**Issue by tomilov** [NVIDIA/thrust#1024]
Is it intentionally, that in the following code `thrust::copy_if` and `thrust::transform_if` behave differently?

```
#include <thrust/functional.h>
#include <thrust/transform.h>
#include <thrust/copy.h>

#include <thrust/iterator/transform_iterator.h>
#include <thrust/iterator/discard_iterator.h>

#include <thrust/device_vector.h>

#include <cstdio>

int main()
{
    thrust::device_vector< int > input{5};
    input[0] = 1;
    input[1] = 2;
    input[2] = 3;
    input[3] = 4;
    input[4] = 5;
    thrust::device_vector< int > stencil{input.size()};
    stencil[0] = 0;
    stencil[1] = 1;
    stencil[2] = 0;
    stencil[3] = 1;
    stencil[4] = 0;
    using namespace thrust::placeholders;
    {
        auto f = [] __host__ __device__ (int i) -> int
        {
            printf("%i copy_if\n", i);
            return i * 100;
        };
        auto input_begin = thrust::make_transform_iterator(input.cbegin(), f);
        thrust::copy_if(input_begin, thrust::next(input_begin, input.size()), stencil.cbegin(), thrust::make_discard_iterator(), _1 == 0);
    }
    {
        auto g = [] __host__ __device__ (int i) -> int
        {
            printf("%i transform_if\n", i);
            return i * 100;
        };
        auto input_begin = thrust::make_transform_iterator(input.cbegin(), g);
        thrust::transform_if(input_begin, thrust::next(input_begin, input.size()), stencil.cbegin(), thrust::make_discard_iterator(), thrust::identity< int >{}, _1 == 0);
    }
}

```
Output:
>  1 copy_if
2 copy_if
3 copy_if
4 copy_if
5 copy_if
1 transform_if
3 transform_if
5 transform_if

Expected output:
> 1 copy_if
3 copy_if
5 copy_if
1 transform_if
3 transform_if
5 transform_if

I expected both above calls must be equivalent.

I think this is a bug in `thrust::copy_if` implementation.

In real life [code](https://gist.github.com/tomilov/2738dc6c1a1afb7ebd2d9892b8a08321#file-sah_kd_tree-cuh-L435) this behaviour of `copy_if` causes a failure of assertion, which normally should be passed successfully. Description of `copy_if` clearly said, that no assignment is done for elements for wich `pred(*stencil)` is `false`. So one expect _whole_ assignment, including iterator dereferencing, is omitted in the case. Dereferencing of iterators for blacklisted elements is wrong, because it may cause e.g. access violation error (say, in case of `permutation_iterator`).

**Comment by miscco** [comment]
I believe this is not a bug but a misunderstanding of the ordering of operations

In your `copy_if` you are checking whether to copy the `transform_iterator` So before `copy_if` can check the condition the `transform_iterator` has already applied the functor.

In contrast `transform_if` checks the condition first and then applies the transformation as per the documentation.

So the different hebavior is indeed as expected and intended
