### ISSUE TITLE
transform_output_iterator not work with lambda

### ISSUE THREAD

**Issue by tomilov** [NVIDIA/thrust#1025]
Cannot compile the following example:
```
#include <thrust/functional.h>
#include <thrust/transform.h>
#include <thrust/copy.h>

#include <thrust/iterator/transform_output_iterator.h>

#include <thrust/device_vector.h>

#include <cstdio>

int main()
{
    thrust::device_vector< int > input{5};
    input[0] = 1;
    input[1] = 2;
    input[2] = 3;
    input[3] = 4;
    input[4] = 5;
    thrust::device_vector< int > stencil{input.size()};
    stencil[0] = 0;
    stencil[1] = 1;
    stencil[2] = 0;
    stencil[3] = 1;
    stencil[4] = 0;
    auto f = [] __host__ __device__ (int i) -> int
    {
        printf("%i\n", i);
        return i * 100;
    };
    thrust::device_vector< int > output{input.size()};
    auto output_begin = thrust::make_transform_output_iterator(output.begin(), f);
    using namespace thrust::placeholders;
    thrust::copy_if(input.cbegin(), input.cend(), stencil.cbegin(), output_begin, _1 == 0);
}
```
Error (VS2017, CUDA v10.1):
> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include\thrust/system/cuda/detail/copy_if.h(836): error : function "thrust::transform_output_iterator<UnaryFunction, OutputIterator>::operator=(const thrust::transform_output_iterator<lambda [](int)->int, thrust::detail::normal_iterator<thrust::cuda_cub::pointer<int>>> &) [with UnaryFunction=lambda [](int)->int, OutputIterator=thrust::detail::normal_iterator<thrust::cuda_cub::pointer<int>>]" (declared implicitly) cannot be referenced -- it is a deleted function

It is inconsistent with behaviour of `transform_iterator`. I believe it also should be at least `Moveable`.

**Comment by jrhemstad** [comment]
https://www.godbolt.org/z/GhP5essqx this no longer appears to be a problem.
