### ISSUE TITLE
Array-oriented access for thrust::complex

### ISSUE THREAD

**Issue by zasdfgbnm** [NVIDIA/thrust#1033]
`std::complex` guarantees array-oriented access behavior:

> For any object `z` of type `complex<T>`, `reinterpret_cast<T(&)[2]>(z)[0]` is the real part of `z` and `reinterpret_cast<T(&)[2]>(z)[1]` is the imaginary part of `z`. For any pointer to an element of an array of `complex<T>` named `p` and any valid array index `i`, `reinterpret_cast<T*>(p)[2*i]` is the real part of the complex number `p[i]`, and `reinterpret_cast<T*>(p)[2*i + 1]` is the imaginary part of the complex number `p[i]`. The intent of this requirement is to preserve binary compatibility between the C++ library complex number types and the C language complex number types (and arrays thereof), which have an identical object representation requirement.

See: https://en.cppreference.com/w/cpp/numeric/complex

Does thrust provide such behavior? This would allow casting between `std::complex` and `thrust::complex` at zero cost using `reinterpret_cast`.

Currently the casting between `std::complex` and `thrust::complex` is host-only:
```C++
__host__ complex (const std::complex< T > &z)
__host__  operator std::complex< T > () const
```

**Comment by jrhemstad** [comment]
I believe `thrust::complex` provides this guarantee, yes.

However, `thrust::complex` is getting replaced with `cuda::std::complex` which definitely guarantees this behavior.
