### ISSUE TITLE
How to copy a thrust::device_vector to a memory of cuda?

### ISSUE THREAD

**Issue by jinfagang** [NVIDIA/thrust#1040]
```
    thrust::device_vector<int> aa;
    int* final_indices;
```

Any way copy a aa to a cuda memory address?

**Comment by hrvthzs** [comment]
Hi,
I am not 100% sure what you want to achive, but I will try to answer your question.
The content of _aa_ is already on the device.  If you want to acquire a raw pointer to the data on the device that you can pass to a kernel then use:
```
int* final_indices = thrust::raw_pointer_cast(aa.data());
my_kernel<<<...>>>(final_indices);
```

If you want to copy data from a raw host pointer to a device pointer, that is also doable. 
```
int* final_indices = ...;
d_ptr = thrust::raw_pointer_cast(aa.data());
cudaMemcpy(d_ptr, final_indices, size, cudaMemcpyHostToDevice);
```

The simplest solution is filling you host_vector first and creating a device_vector by coping it:
```
thrust::host_vector<int> h_vec;
h_vec[0] = ...;
thrust::device_vector<int> d_vec = h_vec;
```

**Comment by jrhemstad** [comment]
Closing as I believe this has been answered. Feel free to reopen if not.
