### ISSUE TITLE
transform_reduce and remove_if do not allow mutation

### ISSUE THREAD

**Issue by elalish** [NVIDIA/thrust#1063]
Is there an algorithmic reason that `transform_reduce` cannot allow the unary functor to change the input sequence? I'm finding myself having to run a `for_each`, followed by a `reduce`, simply because I want the result of the transform to be retained. 

I have a similar problem with `remove_if`; in this case when my functor modifies the input it compiles and runs fine under C++ or OMP (I'm using the CUDA 9.2 version so this works), but with the CUDA backend it complains about const. This seems like an unnecessary restriction.

**Comment by jaredhoberock** [comment]
Yes, the inability to assume immutability of the input would pessimize the performance of these algorithms.

**Comment by elalish** [comment]
@jaredhoberock Wow, even more penalty than running two separate kernels? Anyway, it would be great if these restrictions could be called out more clearly in the documentation, especially since they are different for each backend.

**Comment by prs513rosewood** [comment]
Hey @elalish , I found myself having the same problem a while ago and solved it by using a variant `transform_iterator`:

```cpp
  /// Replacement for thrust::transform_iterator which copies values
  template <typename Iterator, typename Functor, typename Value>
  class transform_iterator
      : public thrust::iterator_adaptor<
            transform_iterator<Iterator, Functor, Value>, Iterator, Value,
            thrust::use_default, thrust::use_default, Value> {
    Functor func;

  public:
    using super_t =
        thrust::iterator_adaptor<transform_iterator<Iterator, Functor, Value>,
                                 Iterator, Value, thrust::use_default,
                                 thrust::use_default, Value>;
    __host__ __device__ transform_iterator(const Iterator& x,
                                           const Functor& func)
        : super_t(x), func(func) {}

    friend class thrust::iterator_core_access;

  private:
    __host__ __device__ auto dereference() const
        -> decltype(func(*this->base())) {
      return func(*this->base());
    }
  };
```

Works fine in OpenMP and TBB, no idea if it works in CUDA though.

**Comment by jrhemstad** [comment]
Closing in favor of https://github.com/NVIDIA/thrust/issues/1871

We will make it a compile time error with a more explicit error message explaining that transformation functions that modify their elements are disallowed. As @jaredhoberock mentioned, it would be problematic if we could not assume the input range is immutable. The most obvious consequence would be that you couldn't dereference an iterator more than once. 

Using a transform_iterator to accomplish the same thing is UB and not recommended.
