### ISSUE TITLE
Cloning thrust from a forked repository fails to update submodule.

### ISSUE THREAD

**Issue by jayeshbadwaik** [NVIDIA/thrust#1119]
Steps to Reproduce:

1. Fork `thrust` but not `cub` to your own user. 
2. Clone `thrust` from the forked user
3. Do a `git submodule update --init`

Expected result: `git submodule update` should work.
Result : `git submodule update` fails

**Comment by allisonvacanti** [comment]
Closing per discussion in #1118.
