### ISSUE TITLE
thrust::reduce and global program optimization flag /GL

### ISSUE THREAD

**Issue by larshg** [NVIDIA/thrust#1127]
Hi

I'm not sure if this is the right place, but it is thrust:reduce instruction which fails, if the GL flag is active and passed to the nvcc.

I have created a MRE [here](https://github.com/larshg/cudathrusttrouble).

If the flag is enabled, the program exits with error code compiled in Release mode. If its off, it run as expected.

Is this flag not fully supported?

Thanks in advance, Lars

**Comment by masterav10** [comment]
I have seen similar behavior with `sort(...)`

> Cuda Samples > 6_Advanced > radixSortThrust

this compiles successfully but fails at runtime from both VS 2017 and VS 2019. Debug mode seems to work fine, regardless of flag.

I have a more detailed information at the linked JavaCPP issue.

**Comment by senior-zero** [comment]
Hello @larshg!

I haven't managed to reproduce the issue with recent CUDA (12.0). 
Please, feel free to reopen if you are still observing the issue on your end.
