### ISSUE TITLE
Update Thrust wiki

### ISSUE THREAD

**Issue by allisonvacanti** [NVIDIA/thrust#1162]
We need to go through the wiki pages and fix/remove out-of-date information.

**Comment by allisonvacanti** [comment]
Assigning @brycelelbach for now, since the fate of the wiki will be determined by the upcoming docs revamp.

**Comment by jnareb** [comment]
The move from <https://http://github.com/thrust/thrust> to <https://github.com/NVIDIA/thrust> failed to move wiki; it is not available **at all**.

The [Quick Start Guide](http://github.com/thrust/thrust/wiki/Quick-Start-Guide) link on the Thrust homepage <https://thrust.github.io/> is therefore dead, or rather does not lead to any useful information.

**Comment by jrhemstad** [comment]
The wiki is no longer used and everything is on the main docs page.
