### ISSUE TITLE
Can a pool memory resource be used to avoid cudaMalloc on each async call?

### ISSUE THREAD

**Issue by anshumang** [NVIDIA/thrust#1188]
In my test, I have two calls to `thrust::async::sort` as below -

```
auto e1 = thrust::async::sort(exec_policy(stream)->on(stream), keys.begin(), keys.end());
auto e2 = thrust::async::sort(exec_policy(stream)->on(stream), keys.begin(), keys.end());
```

I am using a pool memory resource as shown [here](https://github.com/rapidsai/rmm/blob/branch-0.15/include/rmm/mr/device/pool_memory_resource.hpp)

I expect the first call to result in `cudaMalloc` call but the second call to suballocate from the first allocation. However, `cudaMalloc` gets called in both invocations to `thrust::async::sort`.

There could be an issue in the way I am incorporating the pool memory resource. But before looking into that, is this expectation valid?

**Comment by griwes** [comment]
Can you provide a full compilable reproducer?

**Comment by anshumang** [comment]
This is what I have now. This calls `cudaMalloc` on each invocation of `async::sort`.

```
#include <thrust/device_vector.h>
#include <thrust/execution_policy.h>
#include <thrust/detail/type_traits/pointer_traits.h>
#include <thrust/device_malloc_allocator.h>
#include <thrust/async/sort.h>
#include <cstddef>
#include <utility>
#include <atomic>

#define CHECK_CUDA_ERROR(stmt) \
  do { \
      cudaError_t cerr = stmt; \
      if (cerr != cudaSuccess) \
      { \
          std::cout << "cuda call failed" << std::endl; \
      } \
  } while (0);
  
template <typename T>
using device_vector = thrust::device_vector<T, thrust::device_malloc_allocator<T>>;

using par_t         = decltype(thrust::cuda::par(*(new thrust::device_malloc_allocator<char>())));
using deleter_t     = std::function<void(par_t *)>;
using exec_policy_t = std::unique_ptr<par_t, deleter_t>;

inline exec_policy_t exec_policy(cudaStream_t stream = 0)
{
  auto *alloc  = new thrust::device_malloc_allocator<char>();
  auto deleter = [alloc](par_t *pointer) {
    delete alloc;
    delete pointer;
  };

  exec_policy_t policy{new par_t(*alloc), deleter};
  return policy;
}
  
int main(void)
{
  const size_t N = 1024 * 1024;
  thrust::device_vector<int> keys(N);
  
  cudaStream_t stream;
  CHECK_CUDA_ERROR(cudaStreamCreateWithFlags(&stream, cudaStreamNonBlocking));
  
  auto e1 = thrust::async::sort(exec_policy(stream)->on(stream), keys.begin(), keys.end());
  auto e2 = thrust::async::sort(exec_policy(stream)->on(stream), keys.begin(), keys.end());
  auto e3 = thrust::async::sort(exec_policy(stream)->on(stream), keys.begin(), keys.end());
  
  return 0;
}
```

**Comment by pauleonix** [comment]
There is no way for the the different calls to `async::sort` to know about each other and previous allocations in your code. You are also not using a pool resource at all. In today's implementation (not part of the public API) the allocated memory is returned to the caller inside the `device_event`. So in theory one should be able to extract the memory from the event and wrap it with a new allocator. But at this point one would have to touch the `detail` interfaces which could change in the future. I'm trying to find a different solution but found #1718. 

Maybe the implementation could be changed so the algorithms inspect the events they depend on and reuse their memory when possible. Is there anything general speaking against this implementation?

**Comment by jrhemstad** [comment]
As mentioned above, because the `exec_policy()` constructs a new allocator each time, it won't be shared across algorithm invocations.

Furthermore, it doesn't appear the example is using a memory pool in the first place as `thrust::device_malloc_allocator<char>()`.

Feel free to reopen this issue if there is anything that is still unresolved.
