### ISSUE TITLE
Promises & Futures

### ISSUE THREAD

**Issue by jaredhoberock** [NVIDIA/thrust#126]
C++11-style promises & futures provide a natural way to express dependencies among asynchronous launches. Thrust should provide them.

The bulk synchronous launch primitive would return a `future`:

```
template<typename State, typename Function, typename... Args>
future<void> bulk_async(State &state, std::size_t num_groups, std::size_t num_tasks, Function f, Args&&... args);
```

cf. [`std::future`](http://en.cppreference.com/w/cpp/thread/future)
cf. [`std::promise`](http://en.cppreference.com/w/cpp/thread/promise)

Blocked by: Bulk Synchronous Data Parallel Kernel Launch #124

**Comment by Bulat-Ziganshin** [comment]
>It's unclear how to expose the interface of such an algorithm whose arguments are themselves (i.e., first, last, init) futures.

C++ AMP solves this problem by providing its own version of future, that only adds 'then':

http://blogs.msdn.com/b/nativeconcurrency/archive/2012/06/05/10311547.aspx

**Comment by jrhemstad** [comment]
The asynchronous future of Thrust will be built on the foundation of wg21.link/p2300.
