### ISSUE TITLE
Add async transform_reduce and transform_reduce_into algorithms

### ISSUE THREAD

**Issue by brycelelbach** [NVIDIA/thrust#1266]

**Comment by mkre** [comment]
Hi,

This functionality would be very helpful for our application. Any plans on when this will be added to Thrust? 

Thanks,
Moritz

**Comment by mkre** [comment]
Thanks @allisonvacanti. This should allow us to move on with our project. I'll keep an eye on this issue.

**Comment by jrhemstad** [comment]
We have no plans to add additional functionality to `thrust::async` as it is deprecated.
