### ISSUE TITLE
Range-Based Interface

### ISSUE THREAD

**Issue by jaredhoberock** [NVIDIA/thrust#127]
Iterator-based APIs such as Thrust have many [well-known problems](http://www.slideshare.net/rawwell/iteratorsmustgo). In additional to eliminating all of the verbosity of iterators, a range-based API would be composable, eliminating much of the need for specialized "shorthand" algorithms such as `transform_reduce`.

Compare:

```
reduce(transform(vec, f), init, g);
```

to

```
typedef transform_iterator<functor_type, vector<T>::iterator> xfrm_first(vec.begin(), f);
typedef transform_iterator<functor_type, vector<T>::iterator> xfrm_last(vec.end(), f);

reduce(xfrm_first, xfrm_last, init, g);
```

or

```
transform_reduce(vec.first(), vec.last(), f, init, g);
```

The benefits are amplified when zips are necessary. Compare:

```
for_each(zip(A,B,C), ternary_function);
```

to

```
for_each(make_zip_iterator(make_tuple(A.begin(), B.begin(), C.begin(), D.begin())),
         make_zip_iterator(make_tuple(A.end(),   B.end(),   C.end(),   D.end())),
         ternary_function);
```

Thrust should provide a range-based algorithms API in addition to its current iterator-based API, e.g.

```
template<typename RandomAccessRange>
void algo(RandomAccessRange &rng);

template<typename RandomAccessiterator>
void algo(RandomAccessiterator first, RandomAccessiterator last);
```

cf. [RangeLib](http://rangelib.synesis.com.au/)
cf. [Boost.Range](http://www.boost.org/doc/libs/1_49_0/libs/range/doc/html/index.html)
cf. [thrust-range](http://code.google.com/r/jaredhoberock-thrust-range)
cf. [std.range](http://dlang.org/phobos/std_range.html)
cf. [c++1y-range](http://code.google.com/p/cxx1y-range/)
cf. [folly/Range.h](https://github.com/facebook/folly/blob/master/folly/Range.h)

Blocked by:
- c++11 auto type #128
- c++11 rvalue references #129

**Comment by jrhemstad** [comment]
A `<ranges>` implementation is being actively developed in libcu++, see https://github.com/NVIDIA/libcudacxx/pull/358.
