### ISSUE TITLE
thrust-config.cmake is installed in a non-standard location

### ISSUE THREAD

**Issue by germasch** [NVIDIA/thrust#1292]
Usually when configuring a project that provides a cmake package config file with `cmake -DCMAKE_INSTALL_PREFIX=$PFX`, I can later pull that into a downstream project using `find_package(proj)`. In order for it to be found, I set `CMAKE_PREFIX_PATH=$PFX` (well, mostly my package manager does it, but anyway).

Thrust nicely provides a `thrust-config.cmake` now that's installed together with the headers, but the file itself is put into a non-standard location, ie., `$PFX/include/cmake/thrust/thrust-config.cmake`.  `cmake` searches in various locations (see https://cmake.org/cmake/help/latest/command/find_package.html),  but not there. Most commonly I see `$PFX/lib/cmake/pkg/pkg-config.cmake` being used, though since thrust is header-only, maybe `share` instead of `lib` would be more appropriate.

Somewhat related to do this, the Thrust README file recommends using this to help cmake find Thrust:
```
$ cmake . -DThrust_DIR=/usr/local/cuda/include/thrust/cmake/
```

I believe the newer, more standard way of providing paths for a specific package (besides `CMAKE_PREFIX_PATH`) is
```
$ cmake . -DThrust_ROOT=/usr/local/cuda
```
(which again wouldn't work because of the non-standard location of the config file in the include directory)

**Comment by allisonvacanti** [comment]
Thanks for the report. The RAPIDS team pointed this out and I have plans to fix this for local installs of thrust in the near future.

@brycelelbach We should talk about how to fix this in the CTK packages. It looks like the config files aren't present at all right now, they probably need to be added to a glob somewhere in the packaging scripts.

**Comment by germasch** [comment]
So for me this is also triggered by rapids/rmm, though I also would like to have this work cleanly in another project.

So I guess I might as well use the chance to bring up some other questions / issues:

* In https://github.com/NVIDIA/thrust/blob/main/CONTRIBUTING.md, it says that thrust follows (or will follow) semantic versioning. But the way the config is written right now, if I ask for `find_package(Thrust 1.10.0)`, it won't accept 1.11.0, or even 1.10.1. Maybe there's a good reason for it, but it's very restrictive.

* The bigger issue is about how to handle installing a package, like `rapids/rmm`, that uses thrust, either by `add_subdirectory()` or by `find_package()`. This is complicated by two things: The flexibility to create one's own targets also means there's no easy way to coordinate which target will be used if thrust is pulled in multiple times (say by the downstream project directly, and also via rmm). The other thing is that you have this elaborate workaround to avoid `-isystem`, which is obviously important on the one hand, but it also creates trouble when exporting a target that depends on Thrust.

I haven't dug into this deeply yet. In any case, if you'd like to track these issues or have a more in-depth conversation, I'd be happy to open separate github issues for them.

**Comment by allisonvacanti** [comment]
Good stuff, thanks for raising these points.

> In https://github.com/NVIDIA/thrust/blob/main/CONTRIBUTING.md, it says that thrust follows (or will follow) semantic versioning. But the way the config is written right now, if I ask for find_package(Thrust 1.10.0), it won't accept 1.11.0, or even 1.10.1. Maybe there's a good reason for it, but it's very restrictive.

Agreed. We briefly discussed how to handle the `find_package` version compatibility internally, and went with the current approach of:

- `PACKAGE_VERSION_COMPATIBLE=TRUE` when X.Y.Z match, and
- `PACKAGE_VERSION_EXACT=TRUE` when X.Y.Z.W match.

out of an abundance of caution while the new CMake configs and versioning system settled. It's worth revisiting that discussion, so I've opened #1293 to track this. Please review that issue and let me know if my proposal is better aligned with your expectations.

> The bigger issue is about how to handle installing a package, like rapids/rmm, that uses thrust, either by add_subdirectory() or by find_package(). This is complicated by two things: The flexibility to create one's own targets also means there's no easy way to coordinate which target will be used if thrust is pulled in multiple times (say by the downstream project directly, and also via rmm). The other thing is that you have this elaborate workaround to avoid -isystem, which is obviously important on the one hand, but it also creates trouble when exporting a target that depends on Thrust.

Yes, it's sort of a ugly corner that we're backed into because of our inclusion in the toolchain. I'm definitely interested in collecting user feedback and examples of how this can break things for downstream users, and I'm 100% open to suggestions for ways to improve this :)

Can you file a new issue with more details about the difficulties you've had exporting our targets?

**Comment by brycelelbach** [comment]
@allisonvacanti is PACKAGE_VERSION_COMPATIBLE=TRUE the default?

@allisonvacanti if you know what you want installed, sync up with Barry Fujii and Kevin Mittman, they can help.

**Comment by germasch** [comment]
@brycelelbach: If a downstream package says `find_package(Thrust 1.10.0)`, cmake will look for the version script to return `PACKAGE_VERSION_COMPATIBLE==TRUE`. If it says `find_package(Thrust 1.10.0.0 EXACT)`, it'll look for `PACKAGE_VERSION_EXACT==TRUE`.
