### ISSUE TITLE
Reflect semantic version in `find_package` version checks

### ISSUE THREAD

**Issue by allisonvacanti** [NVIDIA/thrust#1293]
Currently, when a downstream consumer calls `find_package(Thrust ...)` and passes an explicit version, we handle version compatibility as follows:

1. If `EXACT` version matching is requested, all four version components (X.Y.Z.W) must match.
2. Otherwise, only the first three components (X.Y.Z) must match.

Our contributor guide specifies that Thrust will follow semantic versioning, and as such the above scheme is too restrictive. According to our stated rules for version increases, I propose moving to the following scheme:

1. If `EXACT` version matching is requested, X.Y.Z.W must match.
2. Otherwise, only X must match, and the package's X.Y.Z.W must be >= the requested X.Y.Z.W.

Thanks to @germasch to pointing this out [here](https://github.com/NVIDIA/thrust/issues/1292#issuecomment-698937388).

Refs:
- [thrust-config-version.cmake](https://github.com/NVIDIA/thrust/blob/7fe07f4e6363c0313d500843b7292b1b55d333f5/thrust/cmake/thrust-config-version.cmake) (as of this issue's filing)
- [CONTRIBUTING.md](https://github.com/NVIDIA/thrust/blob/7fe07f4e6363c0313d500843b7292b1b55d333f5/CONTRIBUTING.md#versioning) (as of this issue's filing)
- [`find_package` version lookup docs](https://cmake.org/cmake/help/latest/command/find_package.html#version-selection)
- [Semantic versioning](https://semver.org/)

**Comment by germasch** [comment]
Thanks for taking up my comment. Just FWIW, as long as you're expecting that the cmake config stuff is still settling down, I think it's reasonable to enforce the stricter compatibility requirements.

The nice thing is that you can make the decision when 1.11.0 (or 1.10.1) is released -- if the config is compatible you can allow `find_package(Thrust 1.10.0)` to accept 1.11.0 by means of the config you distribute with the latter.
