### ISSUE TITLE
exporting targets in downstream users of Thrust

### ISSUE THREAD

**Issue by germasch** [NVIDIA/thrust#1295]
As mentioned in #1292, here are some considerations for using Thrust in a downstream library that itself wants to export its configuration. My particular goal is to make `rapidsai/rmm` installable with a cmake config for easy downstream use, though I'm also facing a similar issue with my own project.

So let's start with the case that works without troubles. Here's a minimal `CMakeLists.txt` for a downstream `mylib` (`test.cxx` can contain whatever).
```cmake
cmake_minimum_required(VERSION 3.17)

project(Test LANGUAGES CXX CUDA)

find_package(Thrust 1.10.0)
thrust_create_target(Thrust)

add_library(mylib SHARED test.cxx)
target_link_libraries(mylib PUBLIC Thrust)

install(TARGETS mylib EXPORT mylib-targets)

install(EXPORT mylib-targets DESTINATION lib/cmake/mylib)
```

cmake will happily `make install` on this, and the generate files are good. In `mylib-targets.cmake`, it's recording
```cmake
set_target_properties(mylib PROPERTIES
  INTERFACE_LINK_LIBRARIES "Thrust"
)
```

which is correct, and which requires me to add this into `mylib-config.cmake`
```cmake
find_dependency(Thrust REQUIRED)
thrust_create_target(Thrust)
```

That's basically following the standard way of doing things (except for the additional `thrust_create_target`). The problem with doing things this way, though, is that that `Thrust` is a custom target name. The downstream application, which uses `mylib`, may also use Thrust directly, in fact that's probably a common case. The downstream app, however, may use it via `thrust_create_target(MyThrust)`, and maybe even with a different configuration or different version. The undesirable consequence is that application will now pull in thrust twice, once directly, and once transitively via `mylib`, and this will probably happen unnoticed by the user.

So I'm not sure what the best way of dealing with this is, in particular without adding a whole lot more complexity. I suppose I could use some variable that can be set before `find_package(mylib)` that, if set, will tell `mylib` to use the thrust target provided, rather than creating its own. That should at least work for header-only mylib, but it does seem pretty fragile.

My thinking was that I could just not use `thrust_create_target(Thrust)` in `mylib`, but use `Thrust::Thrust` directly, which is really all I need, and avoids the issue of `thrust_create_target` and how to name the target entirely. The issue with that is, unfortunately, that I get
```
CMake Error: install(EXPORT "mylib-targets" ...) includes target "mylib" which requires target "_Thrust_Thrust" that is not in any export set.
```

There's an additional problem when using Thrust via `add_subdirectory()`, which will not install Thrust itself as part of the downstream project install, but it's not directly related, so I'll make that a separate issue.

**Comment by allisonvacanti** [comment]
I don't have a lot of familiarity with CMake's export features, so let me know if I'm missing something here.

It sounds like the main issue is a potential name collision where `mylib`'s `Thrust` target and another project's `Thrust` target may have different configurations. AIUI, changing your `Thrust` target to `mylib::Thrust` should fix this:

```
thrust_create_target(mylib::Thrust)
```

I just tested this locally and `thrust_create_target` will create a target in namespace without issue. I'm not sure if that will also have export issues later on, though.

> but use Thrust::Thrust directly, which is really all I need

`Thrust::Thrust` is not a portable target for Thrust configurations that use CUDA, since it will not provide any information about where to locate CUB. It should be treated as an implementation detail that is subject to change without notice.

If you really, really, really want to avoid using `thrust_create_target` and instead use the fragile internal targets, a more robust way would be:

```
find_package(Thrust COMPONENTS CPP CUDA)
target_link_libraries(mylib Thrust::Thrust Thrust::CPP::Host Thrust::CUDA::Device)
```

or the equivalent `add_subdirectory` version:

```
set(THRUST_REQUIRED_SYSTEMS CPP CUDA)
add_subdirectory(thrust)
target_link_libraries(mylib Thrust::Thrust Thrust::CPP::Host Thrust::CUDA::Device)
```

This will probably still have the `"_Thrust_Thrust" that is not in any export set` issue, though.

> There's an additional problem when using Thrust via add_subdirectory(), which will not install Thrust itself as part of the downstream project install, but it's not directly related, so I'll make that a separate issue.

Ah, yeah. I think this would be a pretty easy fix. We can discuss in the new issue.

**Comment by germasch** [comment]
Right, so I think this is due to me using the (internal) targets provided by thrust, which is part of the reason why I'm checking as to whether that's something I should or should not be using. (TL;DR: that wasn't a good idea)

Right now rapids/RMM is using thrust by just adding it to the include path, which is definitely not modern cmake style, but it gets the job done, since all that's needed is to make sure the headers are found. This way makes it possible for the downstream user of RMM to make thrust available in whatever way they want, in particular, they could use `thrust_create_target` and pick a host config. So I was initially kinda hoping to maintain this ability of RMM not really dealing with the details of how thrust should be configured etc and punting it pretty much entirely downstream.

For standard packages, this is less of an issue. During configuration, `find_package()` may end up being called multiple times, but subsequent times will not recreate target if it already exists. This is different here, though, where custom targets are manually created, there's obviously no mechanism to prevent creation of multiple targets under different names, which may or may not correspond to the same configuration.

The issue is not a name clash, that can be prevented relatively easily (as you say, I can use a namespaced target), the issue I was more afraid of is that we may end up with multiple incompatible thrust targets being used for the same executable. And I did manage to get this case to happen, by having RMM linked against default-created `rmm::Thrust`, and then making a custom `Thrust` target in the downstream application, and linking to both the custom target and RMM. 

```cmake
cmake_minimum_required(VERSION 3.18)

project(Test LANGUAGES CXX CUDA)

find_package(rmm REQUIRED)
find_package(Thrust REQUIRED)
thrust_create_target(Thrust HOST OMP DEVICE CUDA)

add_executable(test test.cxx cu.cu)
target_link_libraries(test PRIVATE rmm::rmm Thrust)
```

I'm glad to see that the result is
```
CMake Error: The INTERFACE_THRUST_HOST property of "_Thrust_OMP_Host" does
not agree with the value of THRUST_HOST already determined
for "test".
```
That makes it obvious that there is a problem and also pretty closely hints at what's wrong. I think this is a good solution. If two different configs are asked for, cmake can't work out the answer, it's up to the developer to fix the issue.

So the last remaining issue is, if the downstream application really wants to use a non-default thrust, how can make it have RMM use that custom thrust? I think an easy answer to that is for me to add `thrust_create_target(rmm::Thrust FROM_OPTIONS)`, at which point the downstream project can set the config via cache variables. I actually kinda doubt this is ever going to happen, but I also didn't want to to introduce a way of finding RMM that's too inflexible.

**Comment by allisonvacanti** [comment]
> So the last remaining issue is, if the downstream application really wants to use a non-default thrust, how can make it have RMM use that custom thrust? I think an easy answer to that is for me to add thrust_create_target(rmm::Thrust FROM_OPTIONS), at which point the downstream project can set the config via cache variables. I actually kinda doubt this is ever going to happen, but I also didn't want to to introduce a way of finding RMM that's too inflexible.

You are correct, the `FROM_OPTIONS` setting exists for this use case. It's meant to defer to a user or downstream package for deciding the host/device configuration. Thrust's internal testing harness uses this to allow per-build configuration of these settings.

**Comment by germasch** [comment]
Great, so it turns out that everything's already nicely handled by the thrust cmake config as-is ;)
