### ISSUE TITLE
Use -Wno-deprecated-gpu-targets so that NVCC doesn't complain about deprecated SM archs when compiling every translation unit

### ISSUE THREAD

**Issue by brycelelbach** [NVIDIA/thrust#1316]
@allisonvacanti I'm not sure how best to do this, but can we pass the -Wno-deprecated-gpu-targets flag to NVCC so it doesn't warn about deprecated architectures in our builds?

**Comment by allisonvacanti** [comment]
Sure, I'm planning to do some other CMake work this week, so I'll get that in with the other changes.
