### ISSUE TITLE
CMake files are installed in non-searched location

### ISSUE THREAD

**Issue by kkraus14** [NVIDIA/thrust#1322]
Currently the cmake files are installed in `include/thrust/cmake` which isn't a standard search location: https://cmake.org/cmake/help/v3.18/command/find_package.html#search-procedure

I think projects typically install in `lib/${package_name}/cmake` even if they're header only. I.E. `spdlog` does this today.

**Comment by germasch** [comment]
duplicate of #1292 ;)

**Comment by kkraus14** [comment]
Closing this as a duplicate of #1292 😅
