### ISSUE TITLE
Remove single-config CMake configuration -- always use multiconfig

### ISSUE THREAD

**Issue by allisonvacanti** [NVIDIA/thrust#1333]
Right now there are two ways to build the Thrust/CUB test harness -- single config (only configures a single host/device/dialect configuration) and multiconfig (can configure for multiple host/device/dialect).

My concern is that the single-config path may break without us knowing, since I only use multiconfig builds, as does CI. Since it's redundant with MC, we should just remove the single-config path. There's not a compelling reason to keep it now that MC is well-tested and stable.

By default, only the `cpp.cuda.cpp14` configuration will be generated, just like the current default build. The only difference will be that target/test names will now include the config info, e.g. `thrust.test.scan` will become `thrust.cpp.cuda.cpp14.test.scan`.

**Comment by brycelelbach** [comment]
This sounds good to me - but just a heads up, I'm using the single config in the gpuCI scripts, for the "GPU minimal" configuration for per-commit GPU testing. So, we'll have to remember to update that when this change is made. The update will need to be done in `ci/common/build.bash`.

**Comment by allisonvacanti** [comment]
This is not worth the effort required. We can revisit this if it becomes a significant problem.
