### ISSUE TITLE
Fix documentation for gather.

### ISSUE THREAD

**Issue by tomilov** [NVIDIA/thrust#1342]
Names `map` and `input` are exchanged mistakenly. By sense of `Preconditions` paragraph they have to be exchanged I suppose, because there is no problem when `map` and `result` coincide (in current context).

**Comment by allisonvacanti** [comment]
@tomilov To clarify, you're referring to this part?

```
*  \pre The range <tt>[map_first, map_last)</tt> shall not overlap the range <tt>[result, result + (map_last - map_first))</tt>.
```

suggesting that it should be:

```
*  \pre The range <tt>[input_first, input_last)</tt> shall not overlap the range <tt>[result, result + (map_last - map_first))</tt>.
```

That change makes sense to me, I'll have a PR for it up in a moment.

The rest of the docstring looks ok to me, was there anything else?

**Comment by allisonvacanti** [comment]
I'll actually just add this as an additional precondition. The existing precondition may be necessary for one of the less-commonly-used backend implementations. I'd rather leave it in place for now until this can be tested/validated thoroughly.

**Comment by tomilov** [comment]
Sorry for late answer. Didn't know about dependence on backend. Which one?

**Comment by allisonvacanti** [comment]
I'm not sure whether they do or not at the moment -- I'm just hesitant to remove a precondition without fully verifying the behavior across backends.
