### ISSUE TITLE
how can compile it  with gcc and c++17 ?

### ISSUE THREAD

**Issue by extremety1989** [NVIDIA/thrust#1354]

**Comment by allisonvacanti** [comment]
Can you provide more detail about what you're trying to do, what you've tried, and any issues you've had? We're definitely going to need much more information to help.

**Comment by extremety1989** [comment]
@allisonvacanti i want to use Thrust with NectarCPP/NectarJS, to compile with GCC and not with CL
i tried 

`nvcc -ccbin=g++  -std=c++17 -I libthrust main.cpp src/nectar.cpp -lpthread -o main
nvcc fatal   : nvcc cannot find a supported version of Microsoft Visual Studio. Only the versions between 2013 and 2019 (inclusive) are supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.`

**Comment by allisonvacanti** [comment]
If I remember correctly, the Windows version of `nvcc` will only work with MSVC's `cl` compiler by default, and does not support common Linux compilers like `gcc`.

If you want to use `nvcc` with `gcc` on windows, that's beyond the scope of what the Thrust team can help with here. You'll need to ask for help on the more general CUDA developer forums [here](https://forums.developer.nvidia.com/c/development-tools/cuda-developer-tools/285).

Good luck!

**Comment by extremety1989** [comment]
@allisonvacanti thanks
