### ISSUE TITLE
compile with std_deque errors

### ISSUE THREAD

**Issue by extremety1989** [NVIDIA/thrust#1357]
Hey,
when i compile with "nvcc --compiler-options -std=c++17 -I libthrust main.cpp src/nectar.cpp -lpthread -o main"
i get long error message, but at the end 
`/usr/include/c++/5/bits/stl_deque.h:168:4: error: ‘_M_cur’ was not declared in this scope
  ++_M_cur;
    ^
/usr/include/c++/5/bits/stl_deque.h:169:16: error: ‘_M_last’ was not declared in this scope
  if (_M_cur == _M_last)
                ^
/usr/include/c++/5/bits/stl_deque.h:171:18: error: ‘_M_node’ was not declared in this scope
      _M_set_node(_M_node + 1);
                  ^
/usr/include/c++/5/bits/stl_deque.h:171:29: error: there are no arguments to ‘_M_set_node’ that depend on a template parameter, so a declaration of ‘_M_set_node’ must be available [-fpermissive]
      _M_set_node(_M_node + 1);
                             ^
/usr/include/c++/5/bits/stl_deque.h:172:15: error: ‘_M_first’ was not declared in this scope
      _M_cur = _M_first;
               ^
/usr/include/c++/5/bits/stl_deque.h: In member function ‘NectarCore::NectarCore::NectarCore::NectarCore::NectarCore::NectarCore::NectarCore::NectarCore::NectarCore::NectarCore::NectarCore::NectarCore::NectarCore::NectarCore::NectarCore::std::_Deque_iterator<_Tp, _Ref, _Ptr>::_Self& NectarCore::NectarCore::NectarCore::NectarCore::NectarCore::NectarCore::NectarCore::NectarCore::NectarCore::NectarCore::NectarCore::NectarCore::NectarCore::NectarCore::NectarCore::std::_Deque_iterator<_Tp, _Ref, _Ptr>::operator--()’:
/usr/include/c++/5/bits/stl_deque.h:188:6: error: ‘_M_cur’ was not declared in this scope
  if (_M_cur == _M_first)
      ^
/usr/include/c++/5/bits/stl_deque.h:188:16: error: ‘_M_first’ was not declared in this scope
  if (_M_cur == _M_first)
                ^
/usr/include/c++/5/bits/stl_deque.h:190:18: error: ‘_M_node’ was not declared in this scope
      _M_set_node(_M_node - 1);
                  ^
/usr/include/c++/5/bits/stl_deque.h:190:29: error: there are no arguments to ‘_M_set_node’ that depend on a template parameter, so a declaration of ‘_M_set_node’ must be available [-fpermissive]
      _M_set_node(_M_node - 1);
                             ^
/usr/include/c++/5/bits/stl_deque.h:191:15: error: ‘_M_last’ was not declared in this scope
      _M_cur = _M_last;
               ^
/usr/include/c++/5/bits/stl_deque.h:193:4: error: ‘_M_cur’ was not declared in this scope
  --_M_cur;
    ^
/usr/include/c++/5/bits/stl_deque.h: At global scope:
/usr/include/c++/5/bits/stl_deque.h:203:7: error: expected unqualified-id at end of input
       }
       ^
/usr/include/c++/5/bits/stl_deque.h:203:7: error: expected ‘}’ at end of input`

**Comment by allisonvacanti** [comment]
Not sure what's happening here, these errors are coming from the GCC standard library implementation, not Thrust.

Can you reproduce this with a small, Thrust-only example? If you can narrow this down to specific issue in thrust I'll take a look.

**Comment by extremety1989** [comment]
@allisonvacanti 
first example when i compile  (nvcc index.cu -o index)  it works but when i execute i get error

./index
terminate called after throwing an instance of 'thrust::system::detail::bad_alloc'
  what():  std::bad_alloc: unknown error
Aborted (core dumped)

**Comment by allisonvacanti** [comment]
What is `index.cu`?

**Comment by extremety1989** [comment]
@allisonvacanti arbitrary_transformation.cu

**Comment by allisonvacanti** [comment]
Yes, that of gcc version is supported by thrust.

This is sounding like it may be a WSL issue, since it's working in cmd but not WSL. Are you able to compile and run non-thrust CUDA code in WSL?

**Comment by extremety1989** [comment]
@allisonvacanti yes, i also have VPS Archlinux, i tried to install cuda tool kit, but when i execute 
sudo sh cuda_11.1.1_455.32.00_linux.run
i get following
`Extraction failed.
Ensure there is enough space in /tmp and that the installation package is not corrupt
Signal caught, cleaning up
`
i also checked if enough space avaible

`
[root@vmi290189 /]# df -h
Filesystem      Size  Used Avail Use% Mounted on
dev             3.9G     0  3.9G   0% /dev
run             3.9G  484K  3.9G   1% /run
/dev/sda3       192G   13G  170G   7% /
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           4.0M     0  4.0M   0% /sys/fs/cgroup
/dev/sda1       922M   57M  802M   7% /boot
tmpfs           3.9G     0  3.9G   0% /tmp
tmpfs           797M     0  797M   0% /run/user/0
`

**Comment by allisonvacanti** [comment]
Sorry for the late reply -- The CUDA installer is managed by a different team from Thrust. If you're still having issues with it, your best bet for support is the [NVIDIA developer forums](https://forums.developer.nvidia.com/).
