### ISSUE TITLE
Scan tests with `custom_numeric` fail on NVCC + ICPC with oneTBB as the device backend

### ISSUE THREAD

**Issue by brycelelbach** [NVIDIA/thrust#1367]
When building with the TBB backend using the latest ICPC beta and the version of oneTBB that accompanies it, our scan tests fail:

```
================================================================
FAILURE: TestScanSimpleDevice
[/cccl/thrust/testing/scan.cu:42] Sequences are not equal [type='custom_numeric']
--------------------------------
  [3] custom_numeric{8}  custom_numeric{6}
  [4] custom_numeric{-1}  custom_numeric{1}
--------------------------------
Sequences differ at 2 of 5 positions

================================================================
```

To reproduce, run the following in the root of the repository:

```bash
ci/local/build.bash -i gpuci/cccl:cuda11.0-devel-ubuntu20.04-icclatest -p Thorough thrust.cpp.tbb.cpp11.test.scan
```

Both the C++11 and C++14 variant of the test fail.

**Comment by allisonvacanti** [comment]
Spent a few hours on this today, and these failures look like compiler bugs.

If I compile without optimizations or add debugging statements to the relevant implementation, the tests pass.

(This patch)[https://github.com/allisonvacanti/thrust/commit/646cb53f3d9c7366b971e8a6fad1755232c2bc57] makes some trivial changes that cause current failure to go away. But then a similar failure in a later test case starts blocking the build.

No other compilers are having this issue.

**Comment by allisonvacanti** [comment]
Closing since this only appears to affect a prerelease of ICPC. We can revisit if the bugs continue to appear in an official release of a supported compiler.
