### ISSUE TITLE
Automatic compute architecture detection doesn't update the set of enabled architectures

### ISSUE THREAD

**Issue by brycelelbach** [NVIDIA/thrust#1368]
Because we have a user-settable `option` for each architecture, weird things happen when `cmake` gets rerun if the set of GPUs available to your system changes.

I'm not sure what we want to do about this, if anything, but @allisonvacanti can you give this some thought?

## Example 0

Configure once with GPUs enabled, then configure a second time with GPUs disabled:

```
ci/local/build.bash --clean thrust.example.version
ci/local/build.bash --disable-gpus thrust.example.version
```

First `cmake` run:

```
-- Thrust: Automatically detected compute architectures: sm_35 sm_61 sm_70
-- Thrust: Explicitly enabled compute architectures: sm_35 sm_61 sm_70
-- CUB: Explicitly enabled compute architectures: sm_35 sm_61 sm_70
```

Second `cmake` run:

```
-- Thrust: Automatically detected compute architectures: none
-- Thrust: Explicitly enabled compute architectures: sm_35 sm_61 sm_70
-- CUB: Explicitly enabled compute architectures: sm_35 sm_61 sm_70
```

The architectures aren't disabled even though no GPUs were automatically detected.

## Example 1

Configure once while GPUS are disabled, then configure a second time with GPUs enabled:

```
ci/local/build.bash --clean --disable-gpus thrust.example.version
ci/local/build.bash --disable-gpus thrust.example.version
```

First `cmake` run:

```
-- Thrust: Automatically detected compute architectures: none
-- Thrust: Explicitly enabled compute architectures:
-- CUB: Explicitly enabled compute architectures:
```

Second `cmake` run:

```
-- Thrust: Automatically detected compute architectures: sm_35 sm_61 sm_70
-- Thrust: Explicitly enabled compute architectures:
-- CUB: Explicitly enabled compute architectures:
```

The architectures aren't enabled even though new GPUs have been detected.

**Comment by allisonvacanti** [comment]
Eventually we should ditch the boolean flags and just use the native `CMAKE_CUDA_ARCHITECTURES` system directly. We shouldn't have to worry about mirroring SM state around then, but this will require better NVC++ support in CMake.

https://cmake.org/cmake/help/git-stage/variable/CMAKE_CUDA_ARCHITECTURES.html

**Comment by allisonvacanti** [comment]
Marking as blocked as we can't do anything about this until we have proper nvc++ support in our build system.

**Comment by allisonvacanti** [comment]
Closing this -- we'll be switching to the standard `CMAKE_CUDA_ARCHITECTURE` approach with the switch to a monorepo.
