### ISSUE TITLE
zero copy on embedded devices

### ISSUE THREAD

**Issue by dataplayer12** [NVIDIA/thrust#1375]
I am using thrust on an NVIDIA Jetson embedded device. Since the jetson has the same physical memory for both CPU and GPU, I would like to avoid copying from host to device and back. The usual way of using thrust works fine but the code breaks if I try to use a pointer to the data in the 'CPU address space'. Can you please tell how to do zero copy with thrust on Jetsons?

**Comment by allisonvacanti** [comment]
Closing -- this is being discussed on the mailing list at https://groups.google.com/g/thrust-users/c/_ZdCezDuLeI/m/FHU_G__7AQAJ
