### ISSUE TITLE
missing core dump file 

### ISSUE THREAD

**Issue by dichen16** [NVIDIA/thrust#1394]
Hey NVIDIA developers.
My platform is Fedora 32
- Driver Version: 460.39
- CUDA Version: 11.2
```
#include <iostream>
#include <random>
#include <thrust/inner_product.h>
#include <thrust/execution_policy.h>

int main() {
    // official example
    float vec1[3] = {1.0f, 2.0f, 5.0f};
    float vec2[3] = {4.0f, 1.0f, 5.0f};
    float result = thrust::inner_product(thrust::host, vec1, vec1 + 3, vec2, 0.0f);
    std::cout << result << std::endl;

    unsigned int n = 1000*256*256;
    float *h_x, *h_y;
    // h_x = (float*)malloc(n*sizeof(float));    // culprit for crashdown
    // h_y = (float*)malloc(n*sizeof(float));    // culprit for crashdown
    // fill host array with data
	for(unsigned int i=0;i<n;i++){
		h_x[i] = float(rand()%n) / n;
		h_y[i] = float(rand()%n) / n;
	}
    result = thrust::inner_product(thrust::host, h_x, h_x + n, h_y, 0.0f);
    std::cout << result << std::endl;
    return 0;
}
```
I have set the env variable for debugging, but I did **not** get any coredump output
```
$ export CUDA_ENABLE_COREDUMP_ON_EXCEPTION=1
$ nvcc dot_product.cu -o dot -I /usr/local/cuda/include/ -lcudart -lcuda -L /usr/local/cuda-11.2/lib64/
]$ ./dot 
31
Segmentation fault (core dumped)
```
My question is how to generate the core file. Could any one please give a look?

**Comment by allisonvacanti** [comment]
Per https://docs.nvidia.com/cuda/cuda-gdb/index.html#gpu-coredump, `CUDA_ENABLE_COREDUMP_ON_EXCEPTION` only captures a core dump on a GPU exception, but your example doesn't invoke any CUDA code. The crash is a host-side segmentation fault, not a GPU exception.

In the example provided, the mallocs are commented out, and thus the `for` loop is assigning to invalid pointers. This is likely why you're seeing a segmentation fault.

**Comment by dichen16** [comment]
@allisonvacanti Thanks for your quick reply :D
