### ISSUE TITLE
Disable thrust.test.unittest_static_assert on NVC++

### ISSUE THREAD

**Issue by brycelelbach** [NVIDIA/thrust#1397]
The machinery for the test framework to hook static assertion failures at runtime uses a `__device__` static global, which NVC++ doesn't support. This causes `thrust.test.unittest_static_assert` to fail. 

We need to either disable this test for NVC++ (preferred because it'll take less time and it is not critical to run this test) or fix it.

@griwes wrote it, so we'll make it his problem.

**Comment by brycelelbach** [comment]
This is NVC++ FS 28747

**Comment by allisonvacanti** [comment]
I agree with disabling it. I'll have a PR to fix this in time for 1.13.0.

**Comment by allisonvacanti** [comment]
I'll be doing some other cmake work for 1.13, so I'll just wrap it into that patch. Clearing other assignees.
