### ISSUE TITLE
Replace old SGI links with cppreference.com links in Doxygen

### ISSUE THREAD

**Issue by brycelelbach** [NVIDIA/thrust#1403]
Our Doxygen comments have a lot of references to the old SGI STL docs, which are outdated and no longer available. For example, in [`for_each`](https://github.com/NVIDIA/thrust/blob/main/thrust/for_each.h#L89):

```
 *  \see http://www.sgi.com/tech/stl/for_each.html
```

All of these links should be updated to corresponding [cppreference.com](https://cppreference.com) links.

It's probably not necessary to do all of these updates manually - some clever shell scripting could probably be done to partially automate this task.

**Comment by AdeilH** [comment]
Hey I updated the links but can't seem to link pr with this issue. 

https://github.com/NVIDIA/thrust/pull/1405

**Comment by watmough** [comment]
Or use the symbol index https://en.cppreference.com/w/cpp/symbol_index
