### ISSUE TITLE
Documentation builds on readthedocs?

### ISSUE THREAD

**Issue by indigoviolet** [NVIDIA/thrust#1411]
Hello,

It seems that documentation builds on https://thrust.github.io/doc/modules.html are somewhat out of date.  

For my own use, I experimented with setting up a [readthedocs.org](https://readthedocs.org/) build of the existing doxygen documentation, and it turned out to be [pretty easy]:(https://github.com/NVIDIA/thrust/compare/main...indigoviolet:main) -- most of that diff is just getting a Python virtual environment. 

The resulting build is at https://thrust.readthedocs.io/en/latest/index.html. I'm happy to release this subdomain if someone from the official team wants to take this approach and run with it. I'm also happy to work with someone to submit a PR to get this working here.

Setting this up with readthedocs will provide up to date documentation builds. I have no affiliation with them.

Cheers,

**Comment by allisonvacanti** [comment]
Thanks for looking into this! I appreciate the time you put in here.

@brycelelbach has been working on a large overhaul of our docs, assigning him to make the call as to how we proceed here.

**Comment by jrhemstad** [comment]
We will be removing the old docs website as part of the migrations to docs.nvidia.com under the new docs system.
