### ISSUE TITLE
thrust::{device,host}_vector::reserve() leaks memory

### ISSUE THREAD

**Issue by germasch** [NVIDIA/thrust#1443]
This is most easily reproduced using a `host_vector`, but it's a problem in `vector_base` and hence happens for a `device_vector` as well, which is where I first hit it.

To reproduce:

```cxx
#include <iostream>
#include <thrust/host_vector.h>

int main()
{
    thrust::host_vector<double> v(3);
    std::cout << v.size() << " " << v.capacity() << "\n";
    v.reserve(4);
    std::cout << v.size() << " " << v.capacity() << "\n";

    return 0;
}
```

Run with `valgrind --leak-check=full`:

```
==87208== Memcheck, a memory error detector
==87208== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==87208== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
==87208== Command: ./leak_test
==87208==
3 3
3 6
==87208==
==87208== HEAP SUMMARY:
==87208==     in use at exit: 24 bytes in 1 blocks
==87208==   total heap usage: 23 allocs, 22 frees, 74,312 bytes allocated
==87208==
==87208== 24 bytes in 1 blocks are definitely lost in loss record 1 of 1
==87208==    at 0x4084AF4: operator new(unsigned long) (vg_replace_malloc.c:334)
==87208==    by 0x100064A7: __gnu_cxx::new_allocator<double>::allocate(unsigned long, void const*) (in /autofs/nccs-svm1_home1/kaig1/src/thrust-leak/build/leak_test)
==87208==    by 0x1000613F: std::allocator_traits<std::allocator<double> >::allocate(std::allocator<double>&, unsigned long) (in /autofs/nccs-svm1_home1/kaig1/src/thrust-leak/build/leak_test)
==87208==    by 0x10005DDF: thrust::detail::allocator_traits<std::allocator<double> >::allocate(std::allocator<double>&, unsigned long) (in /autofs/nccs-svm1_home1/kaig1/src/thrust-leak/build/leak_test)
==87208==    by 0x100058E3: thrust::detail::contiguous_storage<double, std::allocator<double> >::allocate(unsigned long) (in /autofs/nccs-svm1_home1/kaig1/src/thrust-leak/build/leak_test)
==87208==    by 0x100054A3: thrust::detail::vector_base<double, std::allocator<double> >::default_init(unsigned long) (in /autofs/nccs-svm1_home1/kaig1/src/thrust-leak/build/leak_test)
==87208==    by 0x10004E3F: thrust::detail::vector_base<double, std::allocator<double> >::vector_base(unsigned long) (in /autofs/nccs-svm1_home1/kaig1/src/thrust-leak/build/leak_test)
==87208==    by 0x10004C03: thrust::host_vector<double, std::allocator<double> >::host_vector(unsigned long) (in /autofs/nccs-svm1_home1/kaig1/src/thrust-leak/build/leak_test)
==87208==    by 0x10004193: main (in /autofs/nccs-svm1_home1/kaig1/src/thrust-leak/build/leak_test)
==87208==
==87208== LEAK SUMMARY:
==87208==    definitely lost: 24 bytes in 1 blocks
==87208==    indirectly lost: 0 bytes in 0 blocks
==87208==      possibly lost: 0 bytes in 0 blocks
==87208==    still reachable: 0 bytes in 0 blocks
==87208==         suppressed: 0 bytes in 0 blocks
==87208==
==87208== For counts of detected and suppressed errors, rerun with: -v
==87208== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```

When using `reserve` to grow a vector, the originally allocated memory does not get deallocated. This is how it happens:

When asking to reserve more memory than currently allocated, `vector_base::reserve()` calls `allocate_and_copy()`, passing the current storage as last argument, which is called `new_storage` in `allocate_and_copy`.

```cxx
template<typename T, typename Alloc>
  void vector_base<T,Alloc>
    ::reserve(size_type n)
{
  if(n > capacity())
  {
    allocate_and_copy(n, begin(), end(), m_storage);
  } // end if
} // end vector_base::reserve()
```

`allocate_and_copy()` then proceeds to call `new_storage.allocate(allocated_size);`. This does not deallocate the currently allocated storage region in `new_storage` (ie., the current storage of the vector), it just allocates a new chunk of memory and saves it in `new_storage` hence overwriting the pointer to the old storage, which is thereby definitely leaked.

It's worth noting that calling `new_storage::deallocate()` beforehand is not a solution -- it would prevent the leak, but it would mean that in order to copy the old vector elements into the new storage one would access now-deallocated storage. (More specifically, in this case calling `::deallocate()` would invalidate the `first`, `last` iterators passed into `allocate_and_copy`.) It may be worth adding a check into `contiguous_storage` that would trigger an exception if allocating an already allocated storage area again, which would catch this kind of bug.

An aside is that the new capacity of the vector ends up being `6` rather than the requested size of `4`. This is caused by the logic growing the storage by at least a factor of 2, which is obviously appropriate when resizing a vector, but not expected on `reserve()` (`std::vector` does in factor end up with a capacity of `4` in this same case). This behavior is actual detrimental in my usage, since I'm using `reserve()` before `resize()` to avoid growing the vector by a factor of 2 when I only need to grow it by much less -- but then it grows by a factor of 2, anyway. But the main problem obviously is the leaked memory.

**Comment by allisonvacanti** [comment]
Can confirm the issue -- thanks for the patch!
