### ISSUE TITLE
[Question] Implementing N-body simulation in thrust

### ISSUE THREAD

**Issue by Fillo7** [NVIDIA/thrust#1449]
I was thinking about implementing N-body simulation in thrust. To do it, I was looking at thrust::transform, but the problem with it is that it uses 1:1 input to output element mapping. In case of N-body, in order to compute output data for one particle, input data from all particles is needed - i.e., N:1 input to output mapping.

Is there an elegant way to do this kind of computation in thrust (by utilizing transform or perhaps some other thrust functionality)? I wasn't able to find anything in documentation or examples.

Thanks.

**Comment by brycelelbach** [comment]
You could do it with a combination of fancy iterators, like zip iterators and counting iterators, which would let you iterate over a multidimensional problem space.
