### ISSUE TITLE
Using current Thrust with older CUDA environment and CMake fails to search newer Thrust

### ISSUE THREAD

**Issue by jwmelto** [NVIDIA/thrust#1466]
I want to use Thrust > 1.12 to take advantage of `universal_vector`. I'm running in a Docker container based on **nvidia/cuda:11.0-devel-centos7**. Inside my container, I do the following commands:

```bash
cd /usr/src
git clone --recurse --single-branch --branch cuda-11.4 https://github.com/NVIDIA/thrust.git
cd thrust
mkdir build
cd build
cmake ..
make install
```

Then I modified my project's top-level CMakeLists.txt to include:
```cmake
find_package(Thrust 1.12.1 REQUIRED CONFIG)
thrust_create_target(Thrust)
```

Then, in a CUDA-using directory, I added modified my CMakeLists.txt to use the Thrust target
```cmake
target_link_libraries( ${myTarget}
  Thrust
  cufft nvidia-ml
)
```

If I just add `<thrust/universal_vector.h>` to a header file of one of my CUDA sources, I get these errors:
```
/usr/local/include/thrust/universal_allocator.h:45:57: error: no member named 'universal_allocator' in namespace 'thrust::system::cuda' [clang-diagnostic-error]
using thrust::system::__THRUST_DEVICE_SYSTEM_NAMESPACE::universal_allocator;
                                                        ^
/usr/local/include/thrust/universal_allocator.h:73:53: error: no template named 'universal_pointer' in namespace 'thrust::system::cuda' [clang-diagnostic-error]
  thrust::system::__THRUST_DEVICE_SYSTEM_NAMESPACE::universal_pointer<T>;
                                                    ^
/usr/local/include/thrust/universal_vector.h:53:57: error: no member named 'universal_vector' in namespace 'thrust::system::cuda' [clang-diagnostic-error]
using thrust::system::__THRUST_DEVICE_SYSTEM_NAMESPACE::universal_vector;
                                                        ^
```

To verify my hypothesis, I modified /usr/local/include/thrust/host_vector.h to include a compile error (`#error this is a bug`). The header I added `thrust::universal_vector` to also includes `<thrust/host_vector.h>`. My induced error is not reached. This leads me to conclude that **nvcc** is finding its own Thrust rather than my installed one.

This may just be a documentation issue, but I can't find how to coerce(!) CMake / nvcc to use my installed Thrust?

**Comment by allisonvacanti** [comment]
How is the compiler being invoked? Check with `VERBOSE=1 make` to see the commands that are being used.

I suspect that this is due to one of the other linked targets (`cufft` or `nvidia-ml`) adding the CUDA toolkit header path before Thrust's include path, so the compile is searching the CUDA installation first. This is consistent with it finding `host_vector` from the CUDA installation, but `universal_vector` from Thrust.

If this is the case, I believe that this can be fixed by separating the `target_link_library` commands to force CMake to add Thrust's link info first:

```
target_link_libraries(${myTarget} Thrust)
target_link_libraries(${myTarget} cufft nvidia-ml)
```

When multiple libraries are linked in a single command, CMake will sometimes reorder them. Splitting up the link commands should force it to preserve the order.

**Comment by jwmelto** [comment]
That's the first I've heard of CMake re-ordering libraries. If that's true, it would be quite concerning. However, I tried what you suggested with no change. The invocation is
```
cd /usr/src/proj/build-Debug/src/dsp && /usr/local/cuda/bin/nvcc -forward-unknown-to-host-compiler 
  -DLINUX -DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CUDA -DTHRUST_HOST_SYSTEM=THRUST_HOST_SYSTEM_CPP 
  -I/usr/src/proj/src -isystem=/usr/src/proj/build-Debug/googletest-src/googletest/include 
  -isystem=/usr/local/cuda/targets/x86_64-linux/include -g --generate-code=arch=compute_35,code=[compute_35,sm_35] 
  --generate-code=arch=compute_60,code=[compute_60,sm_60] -Xcompiler=-fPIC 
  --compiler-options=-fdiagnostics-color=never -Wno-deprecated-gpu-targets --use_fast_math -std=c++17 -x cu 
  -dc /usr/src/proj/src/dsp/FFT.cu -o CMakeFiles/dsp.dir/FFT.cu.o
```
Interestingly, I do see the CUDA include path explicilicitly added, and no evidence of my installed Thrust. Yet it is still finding `<thrust/universal_vector.h>`. Unless /usr/local/include is an implied search path?

**Comment by jwmelto** [comment]
I can change my CMakeLists.txt as needed ... how does anyone else do this?

**Comment by jwmelto** [comment]
```
-- Thrust: TargetInfo: Thrust::Thrust: (1.12.1.0)
-- Thrust: TargetInfo: Thrust::Thrust > ALIASED_TARGET: _Thrust_Thrust
-- Thrust: TargetInfo: Thrust::Thrust > INTERFACE_INCLUDE_DIRECTORIES: /usr/local/include
-- Found Thrust: /usr/local/lib64/cmake/thrust/thrust-config.cmake (found suitable version "1.12.1.0", minimum required is "1.12.1")
-- Thrust: Assembling target Thrust. Options:
-- Thrust: Generating CPP targets.
-- Thrust: TargetInfo: Thrust::CPP: (Thrust 1.12.1.0)
-- Thrust: TargetInfo: Thrust::CPP > ALIASED_TARGET: _Thrust_CPP
-- Thrust: TargetInfo: Thrust::CPP > INTERFACE_LINK_LIBRARIES: Thrust::Thrust
-- Thrust: TargetInfo: Thrust::CPP::Host:
-- Thrust: TargetInfo: Thrust::CPP::Host > ALIASED_TARGET: _Thrust_CPP_Host
-- Thrust: TargetInfo: Thrust::CPP::Host > INTERFACE_COMPILE_DEFINITIONS: THRUST_HOST_SYSTEM=THRUST_HOST_SYSTEM_CPP
-- Thrust: TargetInfo: Thrust::CPP::Host > INTERFACE_LINK_LIBRARIES: Thrust::CPP
-- Thrust: TargetInfo: Thrust::CPP::Host > INTERFACE_THRUST_HOST: CPP
-- Thrust: TargetInfo: Thrust::CPP::Device:
-- Thrust: TargetInfo: Thrust::CPP::Device > ALIASED_TARGET: _Thrust_CPP_Device
-- Thrust: TargetInfo: Thrust::CPP::Device > INTERFACE_COMPILE_DEFINITIONS: THRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CPP
-- Thrust: TargetInfo: Thrust::CPP::Device > INTERFACE_LINK_LIBRARIES: Thrust::CPP
-- Thrust: TargetInfo: Thrust::CPP::Device > INTERFACE_THRUST_DEVICE: CPP
-- Thrust: Searching for CUB REQUIRED
-- Found CUB: /usr/local/lib64/cmake/cub/cub-config.cmake (found version "1.12.1.0")
-- Thrust: Setting CUB target to CUB::CUB
-- Thrust: TargetInfo: CUB::CUB: (1.12.1.0)
-- Thrust: TargetInfo: CUB::CUB > ALIASED_TARGET: _CUB_CUB
-- Thrust: TargetInfo: CUB::CUB > INTERFACE_INCLUDE_DIRECTORIES: /usr/local/include
-- Thrust: TargetInfo: Thrust::CUDA: (CUB 1.12.1.0)
-- Thrust: TargetInfo: Thrust::CUDA > ALIASED_TARGET: _Thrust_CUDA
-- Thrust: TargetInfo: Thrust::CUDA > INTERFACE_LINK_LIBRARIES: Thrust::Thrust;CUB::CUB
-- Thrust: TargetInfo: Thrust::CUDA::Device:
-- Thrust: TargetInfo: Thrust::CUDA::Device > ALIASED_TARGET: _Thrust_CUDA_Device
-- Thrust: TargetInfo: Thrust::CUDA::Device > INTERFACE_COMPILE_DEFINITIONS: THRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CUDA
-- Thrust: TargetInfo: Thrust::CUDA::Device > INTERFACE_LINK_LIBRARIES: Thrust::CUDA
-- Thrust: TargetInfo: Thrust::CUDA::Device > INTERFACE_THRUST_DEVICE: CUDA
-- Thrust: TargetInfo: Thrust: (Thrust 1.12.1.0)
-- Thrust: TargetInfo: Thrust > IMPORTED: TRUE
-- Thrust: TargetInfo: Thrust > INTERFACE_LINK_LIBRARIES: Thrust::CPP::Host;Thrust::CUDA::Device
```

also, given
```cmake
add_library( ${myTarget} STATIC
  FFT.cu
)

target_include_directories( ${myTarget} SYSTEM PUBLIC
  ${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES}
)

target_link_libraries( ${myTarget}
  Thrust
  cufft nvidia-ml
)

set_target_properties( ${myTarget} PROPERTIES
                       CUDA_SEPARABLE_COMPILATION ON
                       POSITION_INDEPENDENT_CODE ON
)

get_target_property(foo ${myTarget} INCLUDE_DIRECTORIES)
message("DOH: dsp INCLUDE [${foo}]")
```

I get
```
DOH: dsp INCLUDE [/usr/src/spds/build-Debug/googletest-src/googletest/include;/usr/src/spds/src;/usr/local/include;/usr/local/cuda/targets/x86_64-linux/include]
```
but I may be pulling the wrong property for a CUDA compile

**Comment by allisonvacanti** [comment]
Looking through the log, the `Thrust` target (generated by your call to `thrust_create_target`) links to the expected host/device interfaces:

```
-- Thrust: TargetInfo: Thrust > INTERFACE_LINK_LIBRARIES: Thrust::CPP::Host;Thrust::CUDA::Device
```

These link to the backend interfaces:

```
-- Thrust: TargetInfo: Thrust::CPP::Host > INTERFACE_LINK_LIBRARIES: Thrust::CPP
-- Thrust: TargetInfo: Thrust::CUDA::Device > INTERFACE_LINK_LIBRARIES: Thrust::CUDA
```

Which correctly link to the `Thrust::Thrust` base interface:

```
-- Thrust: TargetInfo: Thrust::CPP > INTERFACE_LINK_LIBRARIES: Thrust::Thrust
-- Thrust: TargetInfo: Thrust::CUDA > INTERFACE_LINK_LIBRARIES: Thrust::Thrust;CUB::CUB
```

And the `Thrust::Thrust` target has the correct `INTERFACE_INCLUDE_DIRECTORIES` of `/usr/local/include`:

```
-- Thrust: TargetInfo: Thrust::Thrust > ALIASED_TARGET: _Thrust_Thrust
-- Thrust: TargetInfo: Thrust::Thrust > INTERFACE_INCLUDE_DIRECTORIES: /usr/local/include
```

Additionally, your target's include paths are correctly including `/usr/local/include` according to [this comment](https://github.com/NVIDIA/thrust/issues/1466#issuecomment-869972580), but for some reason this isn't getting passed to the compiler ([per this comment](https://github.com/NVIDIA/thrust/issues/1466#issuecomment-868744986)). Why this happens is beyond me.

@robertmaynard Do you have any idea why cmake would drop include paths like this?

**Comment by jwmelto** [comment]
I'm happy to see @robertmaynard here... I tried to post a related issue discourse.cmake.org, but I think work has blocked something that precludes completing posts. Unfortunately, I didn't get back to this today.

Perhaps if I installed thrust in some non-standard location, it might force an include? Is it as simple as `make install INSTALL_ROOT=/opt/nvidia` or something like that?

**Comment by allisonvacanti** [comment]
You can try changing the installation path by setting the `CMAKE_INSTALL_PREFIX` cmake variable, e.g. run `cmake -DCMAKE_INSTALL_PREFIX=/foo/bar/baz/ .` from the build directory and then do `make install` as usual.

**Comment by robertmaynard** [comment]
The `/usr/local/include` is an implicit compiler include path of `nvcc` and will be dropped by CMake for that reason. CMake expects implicit compiler includes to not generate warnings or be internally treated as 'SYSTEM' includes.

The quickest solution is to not install Thrust into `/usr/include` or `/usr/local/include` but something like `/usr/thrust/include/`

**Comment by allisonvacanti** [comment]
@jwmelto We're cleaning up our backlog -- Is Rob's proposed workaround suitable for your usecase? Can we close this?

**Comment by jwmelto** [comment]
I'll say yes. I changed direction to use a newer CUDA, so my specific issue is OBE.
