### ISSUE TITLE
https://thrust.github.io points to http://thrust.github.com, which doesn't exist

### ISSUE THREAD

**Issue by jeffhammond** [NVIDIA/thrust#1497]
https://thrust.github.io/ -> Documentation -> "Thrust API (Doxygen)" uses the link http://thrust.github.com/doc/modules.html, instead of the correct one, http://thrust.github.io/doc/modules.html.

I do not know how to fix this, because https://github.com/NVIDIA/thrust/search?q=%22thrust.github.com%22&type=code shows no reference to thrust.github.com.

<img width="1440" alt="thrust" src="https://user-images.githubusercontent.com/406118/127332144-508f7dab-b713-4206-a909-5fae469a43a3.png">

**Comment by bdice** [comment]
Duplicate issue I just filed -- I suggested a solution and would be happy to help implement it. https://github.com/thrust/thrust.github.com/issues/7

**Comment by bdice** [comment]
This issue has been resolved by https://github.com/thrust/thrust.github.com/pull/8.
