### ISSUE TITLE
Documentation of thrust::for_each erroneously uses std::device_vector

### ISSUE THREAD

**Issue by sdall** [NVIDIA/thrust#1529]
thrust/for_each.h:58 contains "a \p std::device_vector" rather than "a \p thrust::device_vector".

**Comment by untamedImpala** [comment]
@allisonvacanti can you add the "hacktoberfest-accepted" tag?

**Comment by allisonvacanti** [comment]
@untamedImpala I added the tag here too -- I'm not very familiar with how hackoberfest works 😅 Does the tag usually go on the PR or the issue, or does it matter?
