### ISSUE TITLE
Allow Thrust and CUB headers to be nested in a custom directory

### ISSUE THREAD

**Issue by allisonvacanti** [NVIDIA/thrust#1541]
RAPIDS recently ran into a bug where the Thrust headers from a custom install were hidden by the Thrust headers in CTK, despite following the usual advice of including non-CTK Thrust headers with `-I` to override the implicit `-isystem <CTK_INCLUDE_PATH>`. 

This is due to the custom include prefix being used by multiple projects, some of which are `-isystem`, and apparently compilers will use `-isystem` when the same path is specified with both `-I` and `-isystem`. A more detailed description of the issue is in rapidsai/rapids-cmake#98.

Currently, rapids-cmake is working around this by reproducing a copy our install rules, adjusted so that thrust/cub headers are installed to `<prefix>/include/thrust/thrust` and `<prefix>/include/cub/cub`.

We should provide a more robust solution, since it's likely that other users will also encounter this issue, and I don't want to break rapids if our install rules change. We should add some CMake variables to specify this extra directory, something like `THRUST_INSTALL_HEADER_INFIX=thrust` and `CUB_INSTALL_HEADER_INFIX=cub`, or something similar (I'm not sure if there's a more idiomatic way to say "infix" in CMake).

**Comment by allisonvacanti** [comment]
> `set(CUB_INCLUDE_DIR "${thrust_SOURCE_DIR}/cub")`

This is likely the main issue -- that `cub` symlink is a problematic legacy remnant since Windows doesn't support symlinks, which explains why Windows is giving you issues. The CUB headers are not reachable with those include paths on that OS, so it's pulling them from the CTK instead of the git repo.

For cross-platform projects, the CUB include path should be `${thrust_SOURCE_DIR}/dependencies/cub`, as described [here](https://github.com/NVIDIA/thrust#using-thrust-from-your-project).

That said...there is a better way :)

> I am wondering if this is the right way to do things though.

We have CMake packages that provide easier ways to use Thrust and CUB from other CMake projects. See [this file](https://github.com/NVIDIA/thrust/blob/main/thrust/cmake/README.md) for details. If you configure a Thrust target to use CUDA using `thrust_create_target`, it will automatically bring in the correct CUB headers, too.

You may also want to look into the [CMakePackageManager](https://github.com/cpm-cmake/CPM.cmake), which provides a nicer interface around `FetchContent`.

> What's weird is my actions is trying to compile with the latest cuda version, which I thought would mean equivalent latest thrust/cub versions, but I guess that is not a thing.

The version of Thrust/CUB shipped with CTK is usually a couple of versions behind what's available on Github. You can find out which version of Thrust/CUB is in your CTK by referencing [this table](https://github.com/NVIDIA/thrust#releases).

> I tried fixing it by defining THRUST_IGNORE_CUB_VERSION_CHECK

This is unlikely to work reliably. Thrust and CUB are tightly coupled these days, and different versions of the libraries are often incompatible with each other.

Your best bet is to use the CMake packages -- those are configured to avoid most of these issues.

**Comment by neoblizz** [comment]
Sweet, thank you for the resources! That solved my issue.
