### ISSUE TITLE
Template parameter name conflict with termios.h macro definition

### ISSUE THREAD

**Issue by PhilipDeegan** [NVIDIA/thrust#1547]
https://github.com/NVIDIA/thrust/blob/d0c7ade5088b28b86220ac3c9d1ca039ff14d2ca/thrust/type_traits/logical_metafunctions.h#L134

```
/usr/local/cuda-11.4/include/thrust/type_traits/logical_metafunctions.h:135:16: error: expected ',' or '>' in template-parameter-list
template <bool B0, bool... BN>
               ^
/usr/include/bits/termios.h:121:13: note: expanded from macro 'B0'
#define  B0     0000000         /* hang up */
```

I ran into this in my own code not that long.
Happy to make a PR with whatever replacement is chosen.
This file is the only place where "B0" occurs like this

reference: https://man7.org/linux/man-pages/man3/termios.3.html

**Comment by allisonvacanti** [comment]
Fixed by #1548.
