### ISSUE TITLE
how can i use thrust to sort struct array on gpu?

### ISSUE THREAD

**Issue by GeneralJing** [NVIDIA/thrust#1585]
i want to sort a struct array like this:
bool descend_index(const Particle a, const Particle b) {
  return a.cell_idx > b.cell_idx;
}
std::sort(particle_array.begin(), particle_array.end(), descend_index);
can thrust satisfiy the need? and if it can, are there some examples that i can refer to?

**Comment by canonizer** [comment]
Yes, you can use Thrust for that.

Here's the example from the Thrust documentation: https://thrust.github.io/doc/group__sorting_gaef9372b75a6920c67c43150627e74225.html#gaef9372b75a6920c67c43150627e74225

`descend_index()` may work if it is a `__device__` function. If it doesn't, wrapping it into a struct should work:

```
struct descend_index {
  __device__ bool operator()(Particle a, Particle b) const { return a.cell_idx > b.cell_idx; }
};

// particle_array should be e.g. thrust::device_vector
thrust::sort(particle_array.begin(), particle_array.end(), descend_index());
```

Note that when using custom comparators, Thrust uses merge sort.

If you want to use radix sort, you'll need to use CUB and use the `begin_bit` and `end_bit` parameters to select the bits to compare. Note that this would only work if `Particle` is of the same size as one of the built-in integer types (8, 16, 32 or 64 bits), and you'll need to cast the pointers manually.

**Comment by GeneralJing** [comment]
thank you for your explanation. i will try that in my work.

**Comment by elstehle** [comment]
Thank you for posting your question, @GeneralJing. The solution proposed by @canonizer should meet your need, so I will close this issue. Please feel free to reopen, if you have a follow-up question.
