### ISSUE TITLE
thrust::cub conflicting with cub

### ISSUE THREAD

**Issue by warrickb** [NVIDIA/thrust#1601]
The latest version of thrust hoists its version of cub into thrust::cub.  This breaks code that uses thrust and includes cub directly and has 'using namespace thrust' in its .cu source files giving a 'cub ambiguous' error.

**Comment by allisonvacanti** [comment]
This is unfortunate, but was necessary to fix some larger linking issues. The least intrusive workaround for any broken code would be to either

(a) explicitly prefix the cub namespace with global scope (`::cub:`), or
(b) remove the `using namespace thrust;`

I'll update the release notes to make a note of this breaking change.

**Comment by allisonvacanti** [comment]
Thanks again for pointing this out. I've updated the 1.14.0 (which introduced the change) and 1.16.0 (the next release) changelogs with a notice about this change in behavior.
