### ISSUE TITLE
Error when using std::enable_if with thrust::for_each

### ISSUE THREAD

**Issue by neoblizz** [NVIDIA/thrust#1610]
```cpp
#include <thrust/for_each.h>
#include <thrust/iterator/counting_iterator.h>
#include <thrust/device_vector.h>
#include <thrust/host_vector.h>

enum my_enum_t {
  X,  /// for each X
  Y   /// for each Y
};

template <my_enum_t t,
          typename vector_t,
          typename operator_t,
          // error: due to overloading
          std::enable_if_t<t == my_enum_t::X, int> = 0>
void execute(vector_t& v, operator_t op) {
  auto data = v.data().get();
  thrust::for_each(             // for each
      thrust::cuda::par.on(0),  // stream
      v.begin(),                // begin
      v.end(),                  // end
      // Notice how the two lambdas differ (e.g. of how enum could
      // lead to different paths we may want to take.)
      [=] __device__(int x) { op(x); }  // lambda
  );
}

template <my_enum_t t,
          typename vector_t,
          typename operator_t,
          // error: due to overloading
          std::enable_if_t<t == my_enum_t::Y, int> = 0>
void execute(vector_t& v, operator_t op) {
  auto data = v.data().get();
  thrust::for_each(                              // for each
      thrust::cuda::par.on(0),                   // stream
      thrust::counting_iterator<int>(0),         // begin
      thrust::counting_iterator<int>(v.size()),  // end
      // Notice how the two lambdas differ (e.g. of how enum could
      // lead to different paths we may want to take.)
      [=] __device__(int i) { op(data[i] + (i * i)); }  // lambda
  );
}

int main(int argc, char** argv) {
  thrust::device_vector<int> v(10, 1);
  execute<my_enum_t::X>(v, [] __device__(int i) { printf("%d\n", i); });
  execute<my_enum_t::Y>(v, [] __device__(int i) { printf("%d\n", i); });
}
```

Looking for some guidance on a simple example that is giving me the following error:
```
enable_if.cu:29:171: error: ‘__T288’ was not declared in this scope
   29 |   thrust::for_each(             // for each
      |

    ^
enable_if.cu: In function ‘void execute(vector_t&, operator_t)’:
enable_if.cu:46:240: error: ‘__T289’ was not declared in this scope
   46 |   thrust::for_each(                              // for each
      |

                                                                  ^
```

Compilation passes on here (I can't reproduce it on godbolt): https://www.godbolt.org/z/8MKEWdaGh (the actual use case is a bit more complicated but I simplified it). I am not sure what `‘__T288’` and `‘__T289’` here are referring to. If I get rid of the `std::enable_if_t` (and obviously only use one version of the function), I do not get this error.

## System

- SM: 61 (GTX 1080)
- C++ 17
- WSL (Ubuntu 18.04)

```
gcc (Ubuntu 11.1.0-1ubuntu1~18.04.1) 11.1.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0
```

**Comment by jrhemstad** [comment]
This issue is unrelated to Thrust and is one of the (many) limitations of `__device__` lambdas. See [I.6.2. Extended Lambda Restrictions #9](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#extended-lambda-restrictions):

>If the enclosing function is an instantiation of a function template or a member function template, and/or the function is a member of a class template, the template(s) must satisfy the following constraints:
>The template must have at most one variadic parameter, and it must be listed last in the template parameter list.
>**The template parameters must be named.**


The `enable_if_t` is resulting in an unnamed template parameter.

The typical WAR is to use a functor or the return type variant of `enable_if`:
```
template <my_enum_t t,
          typename vector_t,
          typename operator_t>
std::enable_if_t<t==my_enum_t::X> execute(vector_t& v, operator_t op) {
```

**Comment by neoblizz** [comment]
Everything comes back to `__device__` lambdas. 😞 This time I was sure I had read through the limitations, I missed the "The template parameters must be named." Thank you for looking into this!

**Comment by jrhemstad** [comment]
> This time I was sure I had read through the limitations, I missed the "The template parameters must be named."

You're not alone :sweat_smile:. I was plagued by the mysterious `error: ‘__T288’ was not declared in this scope` errors for a year before I realized what the root cause was.
