### ISSUE TITLE
Option in thrust cmake config to enable `EXCLUDE_FROM_ALL TRUE`

### ISSUE THREAD

**Issue by cjnolet** [NVIDIA/thrust#1627]
On the RAFT project, we're calling `thrust_create_target` but finding that thrust is being included in our resulting conda packages. It would be very useful if we could specify `EXCLUDE_FROM_ALL TRUE` as an option somewhere in the thrust cmake configuration process so we can stop thrust from being explicitly installed. In the case of RAFT, we're separating the `runtime header dependencies` (which don't require `nvcc` and can be exposed on public APIs) from the `build header dependencies`, which we don't want to install globally with RAFT. 

If there's a better way to accomplish this within RAFT itself then I'm open to try out any suggestions.

**Comment by allisonvacanti** [comment]
Can you clarify what behavior you're seeing, and what you'd like to see instead?

`EXCLUDE_FROM_ALL` controls whether or not a target is built as part of the default "all" target, but since Thrust is header only, we don't add any build steps in `thrust_create_target`.

If you just want to stop the install, you can prevent Thrust from generating install rules by setting the CMake option [`THRUST_ENABLE_INSTALL_RULES=OFF`](https://github.com/NVIDIA/thrust/blob/main/docs/github_pages/setup/cmake_options.md#generic-cmake-options).

**Comment by cjnolet** [comment]
@allisonvacanti, RAFT is a header-only library as well but it depends on thrust and there are some runtime headers we want to install in the user's environment that are used in public APIs of other RAPIDS projects. I tried setting `THRUST_ENABLE_INSTALL_RULES=OFF` but the Thrust headers still seem to get installed in my environment.

Thus far, I've managed to stop all of our other header-only dependencies from installing by setting `EXCLUDE_FROM_ALL TRUE` on them. `EXCLUDE_FROM_ALL` impacts which targets are installed during the install phase and I've been able to stop the targets (for which I have control) by adding `EXCLUDE_FROM_ALL TRUE` to the end of the `add_library()` call.

**Comment by cjnolet** [comment]
Ah, I see even `rapids-cmake` is in fact setting `THRUST_ENABLE_INSTALL_RULES=OFF` [here](https://github.com/rapidsai/rapids-cmake/blob/branch-22.04/rapids-cmake/cpm/thrust.cmake#L79) so now I'm really stumped. That said, I think this option is what I was looking for. 

Thank again for your help @allisonvacanti

**Comment by allisonvacanti** [comment]
Ah, yeah,`rapids-cmake` disables Thrust's default install rules with that option, but then [adds in its own install rules for Thrust/CUB](https://github.com/rapidsai/rapids-cmake/blob/main/rapids-cmake/cpm/thrust.cmake#L112-L146).

Pinging @robertmaynard for awareness of this usecase.

**Comment by robertmaynard** [comment]
calling `rapids_cpm_thrust( INSTALL_EXPORT_SET ` will enable the install rules we have for Thrust. Not having an `INSTALL_EXPORT_SET` listed will disable the install rules (  documented here: https://docs.rapids.ai/api/rapids-cmake/stable/packages/rapids_cpm_thrust.html not listing ).

If want Thrust headers not installed but still have a dependency on Thrust ( `find_package(Thrust)` ) in the raft-config.cmake. You want to do:
```
rapids_cpm_thrust( NAMESPACE raft )
rapids_export_package(BUILD thrust raft-export)
rapids_export_package(INSTALL thrust raft-export)
```
