### ISSUE TITLE
inclusive_scan_by_key produces incorrect result on Kepler (K80) GPU

### ISSUE THREAD

**Issue by ergpudb** [NVIDIA/thrust#1635]
inclusive_scan_by_key produces an incorrect result in some cases when running on a Kepler GPU.

The attached test program demonstrates this. When compiled with compute capability 3.5 using cuda 11.6 (Linux) and run on a K20 or  K80 (driver 470.103.01), it produces the following output:

```
                                v
DEVICE: 1 1 2 3 1 2 3 1 2 3 1 2 2 1 2 3 1 1 2 3 4 
  HOST: 1 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 1 2 3 4
                                ^
```

Note that the indicated numbers are different between the device calculation and the host calculation.

When compiled with compute capability 8.6 using cuda 11.6 (Linux) and run on an RTX 3070 (driver 510.54), it produces the following output:

```
                                v
DEVICE: 1 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 1 2 3 4 
  HOST: 1 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 1 2 3 4
                                ^
```

Note that the indicated numbers are now the same as expected.

[test.cu.txt](https://github.com/NVIDIA/thrust/files/8309561/test.cu.txt)

**Comment by fkallen** [comment]
Thrust requires the scan operator to be associative. If I am not mistaken, this is not the case in your code.

```
struct count_peers
{
    __host__ __device__
    int operator()(const int& first, const int& second) const
    {
        // if the new value is 0, this is a peer so increment the count
        if (second == 0)
            return first + 1;

        // we've seen a nonzero value so restart the count of peers at 1
        return 1;
    }
};
```

count_peers(count_peers(1,1),0) = count_peers(1,0) = 2
but
count_peers(1, count_peers(1,0)) = count_peers(1, 2) = 1

**Comment by ergpudb** [comment]
Hmm, yes you're right, I guess it just comes down to how the work is being divvied up on the different architectures. Sorry for the trouble.
