### ISSUE TITLE
thrust::system::system_error

### ISSUE THREAD

**Issue by araura2000** [NVIDIA/thrust#1636]
Env: 
xgboost 1.5.2 and 1.2.0
Nvidia P102
NVIDIA-SMI 510.47.03
Driver Version: 510.47.03
CUDA Version: 11.6

Recently I run into such an error when thaining my models. 
xgboost.core.XGBoostError: [20:15:09] ../src/tree/updater_gpu_hist.cu:770: Exception in gpu_hist: [20:15:09] ../src/c_api/../data/../common/common.h:45: ../src/tree/updater_gpu_hist.cu: 724: cudaErrorIllegalAddress: an illegal memory access was encountered
and 
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  device free failed: cudaErrorIllegalAddress: an illegal memory access was encountered
Aborted (core dumped)

I tried downgrading xgboost from 1.5.2 to 1.2.0 but it does not help. 
I also tried upgrading CUDA from 11.4 to 11.6 but it does not help either. 
I don't know how to solve this issue as I almost only write Python code and don't have access to low-level codes. 

Can anyone please help me out?

Thanks!

**Comment by araura2000** [comment]
Update: The issue is solved for now. I just removed the GPU and found a nut on it. The nut was left there last time when I replaced the SSD. I guess it caused a short circuit recently. After removing the nut and reseating the GPU, everything is fine now.

**Comment by wmaxey** [comment]
Closing issue as resolved.
