### ISSUE TITLE
Incorrect example for permutation iterator.

### ISSUE THREAD

**Issue by trivialfis** [NVIDIA/thrust#1660]
https://nvidia.github.io/thrust/api/classes/classthrust_1_1permutation__iterator.html#class-thrustpermutation_iterator

``` c++
#include <thrust/iterator/permutation_iterator.h>
#include <thrust/device_vector.h>
...
thrust::device_vector<float> values(4);
values[0] = 10.0f;
values[1] = 20.0f;
values[2] = 30.0f;
values[3] = 40.0f;
values[4] = 50.0f;
values[5] = 60.0f;
values[6] = 70.0f;
values[7] = 80.0f;
```

I think the correct size should be 8 instead of 4.

**Comment by allisonvacanti** [comment]
You are correct, the vector size is definitely incorrect here. Will fix in a moment.
