### ISSUE TITLE
ADL issue breaks thrust::mismatch

### ISSUE THREAD

**Issue by dkolsen-pgi** [NVIDIA/thrust#1662]
`thrust/detail/mismatch.inl` contains at least two unqualified to call to `mismatch`.  For example:

```
__thrust_exec_check_disable__
template<typename DerivedPolicy, typename InputIterator1, typename InputIterator2>
__host__ __device__
thrust::pair<InputIterator1, InputIterator2> mismatch(const thrust::detail::execution_policy_base<DerivedPolicy> &exec,
                                                      InputIterator1 first1,
                                                      InputIterator1 last1,
                                                      InputIterator2 first2)
{
  using thrust::system::detail::generic::mismatch;
  return mismatch(thrust::detail::derived_cast(thrust::detail::strip_const(exec)), first1, last1, first2);
} // end mismatch()
```

If `thrust::mismatch` is called with iterators from `std::ranges::iota_view<T, T>`, the ADL lookup of the unqualified call can incorrectly resolve to an implementation of `mismatch` within Ranges.  For example, this code:

```
#include <execution>
#include <algorithm>
#include <ranges>
int main() {
  auto v = std::views::iota(0, 100);
  auto r = std::mismatch(std::execution::par, v.begin(), v.end(), v.begin());
}
```

when compiled with `nvc++ -std=c++20 -stdpar` with a GCC 11 standard library, gets this compiler error (among other cascading errors):

```
"/usr/include/c++/11/ranges", line 1030: error: no operator "!=" matches these operands
            operand types are: thrust::detail::execute_with_allocator<thrust::mr::allocator<char, thrust::mr::disjoint_unsynchronized_pool_resource<thrust::devic
e_memory_resource, thrust::mr::new_delete_resource>>, thrust::cuda_cub::execute_on_stream_base> != std::ranges::iota_view<int, int>::_Iterator
        while (__first1 != __last1 && __first2 != __last2
                        ^
          detected during:
            instantiation of "std::pair<_Iter1, _Iter2> std::ranges::__detail::mismatch(_Iter1, _Sent1, _Iter2, _Sent2) [with _Iter1=thrust::detail::execute_with
_allocator<thrust::mr::allocator<char, thrust::mr::disjoint_unsynchronized_pool_resource<thrust::device_memory_resource, thrust::mr::new_delete_resource>>, thrus
t::cuda_cub::execute_on_stream_base>, _Sent1=std::ranges::iota_view<int, int>::_Iterator, _Iter2=std::ranges::iota_view<int, int>::_Iterator, _Sent2=std::ranges:
:iota_view<int, int>::_Iterator]" at line 37 of "/compiler-dir/compilers/include-stdpar/thrust/detail/mismatch.inl"
            instantiation of "thrust::pair<InputIterator1, InputIterator2> thrust::mismatch(const thrust::detail::execution_policy_base<DerivedPolicy> &, InputIt
erator1, InputIterator1, InputIterator2) [with DerivedPolicy=thrust::detail::execute_with_allocator<thrust::mr::allocator<char, thrust::mr::disjoint_unsynchroniz
ed_pool_resource<thrust::device_memory_resource, thrust::mr::new_delete_resource>>, thrust::cuda_cub::execute_on_stream_base>, InputIterator1=std::ranges::iota_v
iew<int, int>::_Iterator, InputIterator2=std::ranges::iota_view<int, int>::_Iterator]" at line 1358 of "/compiler-dir/compilers/
include/nvhpc/algorithm_execution.hpp"
            instantiation of "std::pair<_FIt1, _FIt2> std::__pstl::__algorithm_wrapper_struct<true>::mismatch(_FIt1, _FIt1, _FIt2) [with _FIt1=std::ranges::iota_
view<int, int>::_Iterator, _FIt2=std::ranges::iota_view<int, int>::_Iterator]" at line 2602 of "/compiler-dir/compilers/include/
nvhpc/algorithm_execution.hpp"
            instantiation of "std::__pstl::__enable_if_EP<_EP, std::pair<_FIt1, _FIt2>> std::mismatch(_EP &&, _FIt1, _FIt1, _FIt2) [with _EP=const std::execution
::parallel_policy &, _FIt1=std::ranges::iota_view<int, int>::_Iterator, _FIt2=std::ranges::iota_view<int, int>::_Iterator]" at line 6 of "mismatch.cc"
```

**Comment by brycelelbach** [comment]
This is painful.

We can't make it unqualified, because the entire Thrust backend dispatch mechanism relies on ADL.

**Comment by dkolsen-pgi** [comment]
In testing more than 20 algorithms with Ranges iterators, `mismatch` is the only one that has this problem.  I don't know if `thrust::mismatch` is implemented differently from other Thrust algorithms, or if there is something unusual about how `std::ranges::mismatch` is implemented.

**Comment by dkolsen-pgi** [comment]
Also tracked as NVC++ Flyspray FS#31678

**Comment by ericniebler** [comment]
Strange. `std::ranges::mismatch` should be a global constexpr function _object_, not a function. ADL should not be considering it. I'll look into how `std::ranges::mismatch` is defined, but is it possible that nvc++ has a bug where ADL is erroneously considering function objects? @dkolsen-pgi?

**Comment by dkolsen-pgi** [comment]
@ericniebler  It is not `std::ranges::mismatch` that is found by ADL, it is `std::ranges::__detail::mismatch`.

**Comment by ericniebler** [comment]
Then this is a libstdc++ bug. This should be `__mismatch` to avoid this sort of business. I'll see if the problem still exists.

Still, the question is, what do we do about it, considering that many people in the world are using this broken stdlib? I'll think.

**Comment by dkolsen-pgi** [comment]
Ideally, Thrust would use a different name for its internal implementation functions.  The functions that implement `mismatch` for the various back ends that are called via ADL should be named `mismatch_impl` or `mismatch_thrust` or something else that is not `mismatch`.  That will decrease the chance of ADL misfires.  

That's a really big change, since it should apply to all algorithms, not just `mismatch`.  I don't know if Thrust officially supports extensibility for back ends and execution policies, so I don't know if there is code out there that provides their own `mismatch` that would be broken by this change.

This particular bug only happens when the iterators passed to `thrust::mismatch` are in the `std::ranges::__detail` namespace.  That is not a common situation.  If this is already fixed in future versions of libstdc++, then it is probably not worth changing Thrust to deal with this.

**Comment by allisonvacanti** [comment]
>  I don't know if Thrust officially supports extensibility for back ends and execution policies.

We do support this, so we can't easily change those names.

**Comment by ericniebler** [comment]
It's ok. I think I know how to solve this. We need to define an additional overload of `mismatch` for when the begin and end iterators have the same type. That overload will be preferred to the one in `std::ranges::__detail`.

**Comment by ericniebler** [comment]
Hi @dkolsen-pgi. I'm having trouble repro-ing this problem due to configuration issues. But I _think_ the attached patch should fix it. Can you try and see?

[bug1662.patch.txt](https://github.com/NVIDIA/thrust/files/8544376/bug1662.patch.txt)

**Comment by dkolsen-pgi** [comment]
The patch makes `thrust::system::detail::generic::mismatch` a better match than `std::ranges::__detail::mismatch`, which is good.  But it also makes `thrust::system::detail::generic::mismatch` a better match than `thrust::cuda_cub::mismatch`.  That's bad.  All calls to `thrust::mismatch` are using the generic implementation that falls back to using `thrust::find_if_not`.  The CUDA-specific version of `mismatch` is never being called.

I wouldn't have noticed this, since it seems to be a performance issue (and probably a minor one) rather than a correctness issue.  Except that one of the calls to `mismatch` in one of our tests uses an element type that causes the kernel for `find_if_not` to blow up.  That's a bug (in Thrust, in the stdpar framework, or in the test code) that we haven't noticed before.  I will need to investigate that bug.  But it is unrelated to this problem with `mismatch`.

**Comment by ericniebler** [comment]
> But it also makes `thrust::system::detail::generic::mismatch` a better match than `thrust::cuda_cub::mismatch`.

I'm having trouble finding where this overload is defined. @dkolsen-pgi, can you point me in the right direction?

**Comment by dkolsen-pgi** [comment]
`thrist::cuda_cub::mismatch` is defined in `thrust/system/cuda/detail/mismatch.h`

**Comment by ericniebler** [comment]
I see it now, thanks. I can't think of a clever way to avoid selecting the `mismatch` overload in `std::ranges::detail` while _also_ ensuring that `thrust::cuda_cub::mismatch` is preferred over `thrust::system::detail::generic::mismatch`. Considering that this is a bug in libstdc++ (not in Thrust), and that the bug is already fixed upstream, I recommend we leave this one alone.

**Comment by dkolsen-pgi** [comment]
> I recommend we leave this one alone.

I agree with that assessment.

**Comment by allisonvacanti** [comment]
Closing per above discussion (this is a resolved issue in libstdc++).
