### ISSUE TITLE
Wrong documentation for `upper_bound`

### ISSUE THREAD

**Issue by ttnghia** [NVIDIA/thrust#1665]
Let's look at the documentation for `upper_bound`: https://thrust.github.io/doc/group__vectorized__binary__search_gabe5e2b1b20a3e1066d52a9831e20abe5.html#gabe5e2b1b20a3e1066d52a9831e20abe5

The description says: ` Specifically, it returns the index of first position where value could be inserted without violating the ordering.`. This is wrong. In particular, `first position` is wrong. The correct one should be `last position` for `upper_bound`.

**Comment by allisonvacanti** [comment]
This has been corrected in the current version of the new Thrust docs here: https://nvidia.github.io/thrust/api/groups/group__binary__search.html#function-upper-bound

We're in the process of updating our documentation site. The old docs will be removed and all links will be updated once the new docs are ready. In the meantime, the new docs at https://nvidia.github.io/thrust are usable and reflect the current state of the code. Sorry for any confusion -- we hope to finish this migration soon.
