### ISSUE TITLE
Create host_vector or device_vector according to iterator type in Thrust

### ISSUE THREAD

**Issue by shansong99** [NVIDIA/thrust#1668]
I have a function that has Input Iterators as input parameters. They are iterators of either host_vector or device_vector.

I would like to create a temporary vector to store temporary results in this function.
The temporary vector should be the same as what the iterators are for. (if iterators are for device_vector, the temporary vector should also be device_vector, and vice versa)

The question is, How can I get the information from the iterator on whether the iterator is for host_vector or device_vector?
I can come up with below method, but I would like to know if there is better option:

```c++
template<typename InputIterator, typename OutputIterator>
bool my_function(InputIterator begin, InputIterator end, OutputIterator output) {

    if constexpr (std::is_same<thrust::iterator_system<InputIterator>::type, thrust::device_system_tag>::value)
        thrust::device_vector<InputIterator::value_type> temp_vector;
    else
        thrust::host_vector<InputIterator::value_type> temp_vector;

    /*do the rest work*/
}
```

Thanks for recommendations!

**Comment by jrhemstad** [comment]
> How can I get the information from the iterator on whether the iterator is for host_vector or device_vector

Querying the `iterator_system` is the right way to do this. 

@allisonvacanti or @griwes will correct me if I'm wrong, but I think you need to check for `is_convertible` to `device_system_tag` as opposed to `is_same`. 

Otherwise, any solution I can think of effectively boils down to what you already have. I'd probably do it like this, but it's just the same thing spelled in a different way:

```
template<typename InputIterator, typename OutputIterator>
bool my_function(InputIterator begin, InputIterator end, OutputIterator output) {

template <typename T> 
using temp_vec_t = std::conditional_t< std::is_convertible<thrust::iterator_system_t<InputIterator>, thrust::device_system_tag>, 
                                       thrust::device_vector<T>,
                                       thrust::host_vector<T>>;

temp_vec_t<typename thrust::iterator_traits<InputIterator>::value_type> temp_vector;

/* do the rest of the work */
}
```

**Comment by allisonvacanti** [comment]
@jrhemstad's answer is correct. Closing this, but let us know if there's anything else.

**Comment by shansong99** [comment]
indeed it works. and with std::conditional() it seems like a better fit into the code too. thanks for the recommendation!
