### ISSUE TITLE
Reduction function with lvlaue reference parameters should be a compilation error

### ISSUE THREAD

**Issue by dkolsen-pgi** [NVIDIA/thrust#1686]
This code compiles cleanly with NVCC.  It should be a compilation error.  The reduction function takes it's parameters by lvalue reference.  But the arguments to the reduction function are the result of the transformation function, which in this case are not lvalues.  Fixing this will result in problematic code being caught at compile time rather leaving the user puzzling over strange runtime behavior.  I am guessing that fixing this requires adding `std::move` (or equivalent) in the right places, though I don't know where those places are.

```
#include <stdio.h>
#include <thrust/host_vector.h>
#include <thrust/device_vector.h>
#include <thrust/transform_reduce.h>

struct trans_op {
  __device__ int operator()(int z) const { return z + 1; }
};
struct reduce_op {
  __device__ int operator()(int& x, int& y) const { return x + y; }
};

int main() {
  thrust::host_vector<int> hv(1000, 2);
  thrust::device_vector<int> dv(hv);
  int sum = thrust::transform_reduce(dv.begin(), dv.end(), trans_op(), 0, reduce_op());
  printf("%d\n", sum);
}
```

This bug was originally reported against `nvc++ -stdpar`.  See NVBug 3631502.

The Thrust OpenMP back end does not appear to have this problem, at least not with `thrust::transform_reduce`.  I get a compilation error as expected when compiling the test in NVBug 3631502 with `nvc++ -stdpar=multicore`.  I haven't tried any back ends other than CUDA and OpenMP.

**Comment by senior-zero** [comment]
@dkolsen-pgi according to the standard, reduction operator should not modify the arguments. We are planning to [make it](https://github.com/NVIDIA/cub/issues/602) a compilation error in CUB and therefore in Thrust. Please, let us know if you are fine with the solution so we can close this issue.

**Comment by dkolsen-pgi** [comment]
Making it a compilation error was my original request.  I am fine with that solution.

**Comment by senior-zero** [comment]
Since the change in CUB will propagate to Thrust, I'm closing the issue as a duplicate. For other algorithms I've filed the following [issue](https://github.com/NVIDIA/thrust/issues/1871).
