### ISSUE TITLE
ci ERROR on NVIDIA Jetson nano(4GB) 

### ISSUE THREAD

**Issue by shiyi23** [NVIDIA/thrust#1729]
when I run the build.sh under the ci/local, I got the following error message:
`
cuda11.5.1-devel-ubuntu20.04-gcc9: Pulling from gpuci/cccl
Digest: sha256:c5c1f5e1534287be3fa48a0896c40b470cfc76abfd6ba6505c437cf131802663
Status: Image is up to date for gpuci/cccl:cuda11.5.1-devel-ubuntu20.04-gcc9
[docker.io/gpuci/cccl:cuda11.5.1-devel-ubuntu20.04-gcc9](http://docker.io/gpuci/cccl:cuda11.5.1-devel-ubuntu20.04-gcc9)
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
standard_init_linux.go:228: exec user process caused: exec format error
`
and when I edit the build.sh , add a line:  --platform linux/arm64/v8
`......
 docker run --rm -it ${GPU_OPTS} \
+  --platform linux/arm64/v8 \
   --cap-add=SYS_PTRACE \
   --user "$(id -u)":"$(id -g)" \
   -v "${REPOSITORY_PATH}":"${REPOSITORY_PATH_IN_CONTAINER}" \
......
`
and rerun the build.sh,   I got the follow ERROR message:
`
cuda11.5.1-devel-ubuntu20.04-gcc9: Pulling from gpuci/cccl
Digest: sha256:c5c1f5e1534287be3fa48a0896c40b470cfc76abfd6ba6505c437cf131802663
Status: Image is up to date for gpuci/cccl:cuda11.5.1-devel-ubuntu20.04-gcc9
[docker.io/gpuci/cccl:cuda11.5.1-devel-ubuntu20.04-gcc9](http://docker.io/gpuci/cccl:cuda11.5.1-devel-ubuntu20.04-gcc9)
Unable to find image 'gpuci/cccl:cuda11.5.1-devel-ubuntu20.04-gcc9' locally
cuda11.5.1-devel-ubuntu20.04-gcc9: Pulling from gpuci/cccl
Digest: sha256:c5c1f5e1534287be3fa48a0896c40b470cfc76abfd6ba6505c437cf131802663
Status: Image is up to date for gpuci/cccl:cuda11.5.1-devel-ubuntu20.04-gcc9
docker: Error response from daemon: image with reference gpuci/cccl:cuda11.5.1-devel-ubuntu20.04-gcc9 was found but does not match the specified platform: wanted linux/arm64/v8, actual: linux/amd64.
See 'docker run --help'.
huang@huang-desktop:/opt/thrus
`
So, how can I fix this? @allisonvacanti

**Comment by allisonvacanti** [comment]
The scripts in `ci/...` are mainly for developers and our CI testing infrastructure to use, and aren't intended for users. The docker images used by those scripts do not currently support ARM platforms.

Thrust is a header-only library -- there's no binary library component to build, so users generally won't need to build anything directly out of the Thrust repo. To use Thrust, just include our headers from your project and build your project. See [this section](https://github.com/NVIDIA/thrust#getting-the-thrust-source-code) of the docs for more info.

If you'd like to build the Thrust tests, etc on a non-x86 platform like Jetson, the manual build instructions in the second code block of [this section](https://github.com/NVIDIA/thrust#developing-thrust) may be used, but this isn't necessary to use Thrust as an end-user.
