### ISSUE TITLE
Deprecated Type Trait Primitives

### ISSUE THREAD

**Issue by pca006132** [NVIDIA/thrust#1743]
According to https://github.com/llvm/llvm-project/blob/release/13.x/clang/docs/LanguageExtensions.rst#type-trait-primitives, `__has_trivial_copy` and `__has_trivial_constructor` are deprecated. This causes warnings and turned into hard errors when compiled using `-Werror`. Should be simple to fix.

**Comment by miscco** [comment]
I see that there is some conditional compilation for gcc < 4.3 

Do we still support those ancient compilers or could we just clean the whole thing up in a go?

**Comment by senior-zero** [comment]
@miscco Thrust supports GCC 5+

**Comment by allisonvacanti** [comment]
> could we just clean the whole thing up in a go?

We could definitely do quite a bit of cleanup in this area. We can consider this for 2.1.

**Comment by elalish** [comment]
Any hope we can get a fix for this to sneak in? We've been having to manually patch Thrust for months now just to get it to compile: https://github.com/elalish/manifold/blob/master/thrust.diff

**Comment by senior-zero** [comment]
@pca006132 @elalish I'm sorry; while fixing something else, I [removed](https://github.com/NVIDIA/thrust/commit/c3678ce1d1f6bc19d175d20d4402ba61d21d89c9) `__has_trivial_copy` and `__has_trivial_constructor` and completely forgot about this issue. I'm closing it but feel free to reopen in case you still observe related warnings.

**Comment by elalish** [comment]
Excellent, thanks for letting us know!
