### ISSUE TITLE
Fix thrust linkage

### ISSUE THREAD

**Issue by senior-zero** [NVIDIA/thrust#1788]
The issue is related to the following [one](https://github.com/NVIDIA/cub/issues/545). It was recently addressed in [CUB](https://github.com/NVIDIA/cub/pull/547). Thrust has to inherit the namespace solution for the CUDA backend.

**Comment by senior-zero** [comment]
This seems to be needed in 1.17.X as well.

**Comment by jrhemstad** [comment]
I'm going to go ahead and say that we can fix this when we extra Thrust kernels into CUB and let's not bother worrying about fixing the kernels in Thrust. Feel free to reopen if you disagree.
