### ISSUE TITLE
Install rules: PATTERN thrust-header-search EXCLUDE doesn't behave as expected

### ISSUE THREAD

**Issue by robertmaynard** [NVIDIA/thrust#1790]
The `PATTERN` rules in CMake only matches complete file names, and doesn't do globbing. So the current install rules fails to exlude anything.

What we need to do is use `REGEX thrust-header-search.* EXCLUDE`

**Comment by anbe42** [comment]
likewise for cub

**Comment by robertmaynard** [comment]
Closing this is fixed in `main` now: https://github.com/NVIDIA/thrust/pull/1825

fixed in cub as well: https://github.com/NVIDIA/cub/pull/590
