### ISSUE TITLE
Thrust accesses illegal memory when using custom struct

### ISSUE THREAD

**Issue by vyasr** [NVIDIA/thrust#1801]
I'm seeing illegal memory accesses with thrust when used on a container of custom structs. For context, I have an application where I want to run thrust algorithms on a vector-like container that requires trivially copyable types (which `thrust::pair` is not), so as first pass I defined my own simple struct with the necessary operators. However, the resulting code results in a `cudaErrorIllegalAddress`. 

[This tarball](https://github.com/NVIDIA/thrust/files/9667851/thrust_illegal_access.tar.gz) contains a MWE consisting of a single cu file demonstrating the problem along with a CMakeLists.txt file that can be used to compile the code easily against any version of thrust etc. Running

```
tar -xzf thrust_illegal_access.tar.gz
mkdir build
cd build
cmake .. -GNinja # or whatever generator
ninja
```

should generate a suitable executable `TestFile` in the build directory.

I observe the same error on:
- thrust versions 1.15.0, 1.17.2, and on the main branch
- Drivers 495.44, 515.65.01
- Tesla T4 and RTX 8000

I also note that the error only occurs when the code is compiled for a CUDA architecture >= sm 60. I do not observe the error when compiling for sm 52/53, for instance. You can also test this by modifying the line setting `CMAKE_CUDA_ARCHITECTURES` in the included CMakeLists.txt file.

For convenience, here is an abbreviated version of the test file in the tarball. I've excised much of the helpful commentary to keep this comment short, but the code is identical:
```
#include <thrust/device_vector.h>
#include <thrust/sort.h>
#include <thrust/transform.h>

#include <algorithm>
#include <random>
#include <vector>

using T = int32_t;

struct simple_pair {
  T first{};
  T second{};
  __host__ __device__ simple_pair() {};
  __device__ simple_pair(T const& first, T const& second) : first(first), second(second) {};
};

__device__ inline bool operator< (const simple_pair& lhs, const simple_pair& rhs) {
    return (lhs.first < rhs.first) && (lhs.second < rhs.second);
}

int main() {
    auto const min_error_size = 10969; // Fails for >=10969

    std::vector<T> left(min_error_size);
    std::vector<T> right(min_error_size);
    std::iota(left.begin(), left.end(), 0);
    std::iota(right.begin(), right.end(), 0);
    std::mt19937 gen(0);
    std::shuffle(left.begin(), left.end(), gen);
    std::shuffle(right.begin(), right.end(), gen);

    thrust::device_vector<T> d_left(left.size());
    cudaMemcpy(d_left.data().get(), left.data(), left.size() * sizeof(T), cudaMemcpyHostToDevice);
    thrust::device_vector<T> d_right(right.size());
    cudaMemcpy(d_right.data().get(), right.data(), right.size() * sizeof(T), cudaMemcpyHostToDevice);

    auto result_pairs = thrust::device_vector<simple_pair>(min_error_size);
    thrust::transform(thrust::device,
                    d_left.begin(),
                    d_left.end(),
                    d_right.begin(),
                    result_pairs.begin(),
                    [] __device__ (T first, T second) {
                    //return simple_pair{0, 0}; // Works
                    //return simple_pair{first, 0}; // Works
                    //return simple_pair{0, second}; // Works
                    return simple_pair{first, second}; // Fails
                    });

    // This sort call fails, but works if we change the return values in the transform lambda.
    thrust::sort(thrust::device, result_pairs.begin(), result_pairs.end());
}
```

**Comment by senior-zero** [comment]
Hello, @vyasr! I was unable to reproduce the issue on the main branch. Just to make sure, if you mark your transform lambda as `__host__ __device__` does it fix the issue?

**Comment by davidwendt** [comment]
The cmake version required in the attached example is 3.20.1. You can also use this command line option
```
nvcc -std=c++17 --generate-code=arch=compute_75,code=[compute_70,sm_70] --expt-extended-lambda test.cu -o TestFile
```

**Comment by davidwendt** [comment]
Fixing the `operator<` worked for me.

**Comment by vyasr** [comment]
Good catch... yes, I can confirm that changing the operator definition to 
```
__device__ inline bool operator< (const simple_pair& lhs, const simple_pair& rhs) {
    if (lhs.first > rhs.first) return false;
    return (lhs.first < rhs.first) || (lhs.second < rhs.second);
} 
```
resolves the issue.

I understand that `thrust::sort` requires a strict weak ordering, so it's not surprising that the results would be incorrect with an invalid operator, but a crash like this seems like very surprising behavior. Is this just one of those cases where from a thrust API point of view the behavior is UB and anything goes, in which case I can close this issue, or should this issue be left open for thrust to change the behavior from a crash to just producing invalid results (which is what I expected would happen with this kind of user error)?

**Comment by griwes** [comment]
It's UB and anything goes. Checking for whether the provided ordering is valid for the input set would be an extremely expensive operation, so the code just assumes it's valid and rolls with it - and honestly a crash is much nicer of a result than it could be (like corrupting your data or failing to sort it), because you get obvious feedback that something went very wrong.

**Comment by vyasr** [comment]
I agree, we definitely don't want to check the validity of the operator. I don't know thrust internals so I would just naively be concerned that being able to cause a crash in this manner could indicate a bug that could arise even with a valid operator in some cases (as opposed to just generating invalid results). You're definitely right that the error definitely helped pinpoint my mistake a lot faster than generating invalid outputs would have, so I'm fine closing this if you are.

**Comment by vyasr** [comment]
Oh and also just to close the loop @senior-zero no, marking the lambda as `__host__ __device__` doesn't fix the issue (unsurprising given @griwes diagnosis above).
