### ISSUE TITLE
Including thrust host vector seems to require cuda

### ISSUE THREAD

**Issue by wajihboukaram** [NVIDIA/thrust#1807]
I am now getting fatal errors when compiling a host only project using the main branch of thrust.

```
In file included from /home/wajih/codes/thrust/thrust/iterator/iterator_facade.h:36,
                 from /home/wajih/codes/thrust/thrust/iterator/iterator_adaptor.h:36,
                 from /home/wajih/codes/thrust/thrust/iterator/detail/normal_iterator.h:27,
                 from /home/wajih/codes/thrust/thrust/detail/vector_base.h:25,
                 from /home/wajih/codes/thrust/thrust/host_vector.h:27,
                 from test_unique.cpp:1:
/home/wajih/codes/thrust/thrust/detail/type_traits.h:27:10: fatal error: cuda/std/type_traits: No such file or directory
   27 | #include <cuda/std/type_traits>
      |          ^~~~~~~~~~~~~~~~~~~~~~

```

In older versions, it was possible to use thrust as a standalone library if host functionality was all that was needed.

**Comment by jrhemstad** [comment]
Howdy @wajihboukaram. Thanks for reaching out.

What you are seeing is that Thrust and CUB now depend on [libcu++](https://github.com/NVIDIA/libcudacxx) to replace some of Thrust's previously custom Standard Library functionality. 

While libcu++ may be provided by the CUDA toolkit, that is not required. If you are acquiring Thrust from GitHub, then libcu++ was also added as a sub-module of the Thrust repository. 

How are you acquiring Thrust in your project?

**Comment by wajihboukaram** [comment]
Thanks for the quick reply! The above error shows up when I do a regular clone. When I do the recursive clone from the README

`git clone --recursive https://github.com/NVIDIA/thrust.git`

I get the following errors:
`In file included from /home/wajih/codes/thrust/thrust/system/cuda/detail/execution_policy.h:35,
                 from /home/wajih/codes/thrust/thrust/iterator/detail/device_system_tag.h:23,
                 from /home/wajih/codes/thrust/thrust/iterator/detail/iterator_facade_category.h:22,
                 from /home/wajih/codes/thrust/thrust/iterator/iterator_facade.h:37,
                 from /home/wajih/codes/thrust/thrust/iterator/iterator_adaptor.h:36,
                 from /home/wajih/codes/thrust/thrust/iterator/detail/normal_iterator.h:27,
                 from /home/wajih/codes/thrust/thrust/detail/vector_base.h:25,
                 from /home/wajih/codes/thrust/thrust/host_vector.h:27,
                 from test_unique.cpp:1:
/home/wajih/codes/thrust/thrust/system/cuda/config.h:33:10: fatal error: cub/util_namespace.cuh: No such file or directory
   33 | #include <cub/util_namespace.cuh>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
`
I did see that the libcudaxx and cub dependencies were recursively cloned as well though. Do I maybe need to add those to the include path?

**Comment by wajihboukaram** [comment]
Ah I see that I need to set the device system to something other than cuda to get rid of that. 
It's a bit cumbersome, but I can live with it.

**Comment by elalish** [comment]
I hit exactly this issue as well when attempting to update to thrust 2.1 (from 1.15). My project is CMake-based, and after updating thrust I also updated its submodules. However, it still can't find `cuda/std/type_traits`. The release notes claim no change should be needed, and even when I explicitly add the paths to libcudaxx and cub to `target_include_directories` the error remains. I'm on CMake 3.25.2 on OSX (not compiling for GPU on this machine). What am I missing?

**Comment by pca006132** [comment]
nvm, the failure we have for manifold is due to improper CMake configuration
