### ISSUE TITLE
strided sum of a vector

### ISSUE THREAD

**Issue by ztdepztdep** [NVIDIA/thrust#1829]
I have combine many dense vectors with the same dimensions into on large vector. [b0,b1,b2,b3].
I need to compute the sum of all the vector , i.e. b0+b1+b2+b3. 
which api should i use to complete this tast.

**Comment by jrhemstad** [comment]
So you want to compute the sum of all elements across all vectors? Or you want to sum each vector independently?

If the former, then [`thrust::reduce` ](https://nvidia.github.io/thrust/api/groups/group__reductions.html#function-reduce) is what you want. 

If the latter, then [`thrust::reduce_by_key`](https://nvidia.github.io/thrust/api/groups/group__reductions.html#function-reduce-by-key) is what you'd want.

**Comment by jrhemstad** [comment]
Closing due to no response. Feel free to reopen if you still have a question.
