### ISSUE TITLE
`thrust::device_vector` should have an `std::initializer_list` constructor

### ISSUE THREAD

**Issue by Eren121** [NVIDIA/thrust#1835]
Currently, its not possible to do:

```
thrust::device_vector<int> v{4, 8, 0, 8, 4, 2, 8};
```

But instead we need to do:

```
thrust::device_vector<int> v{std::vector<int>{4, 8, 0, 8, 4, 2, 8}};
```

Because there are no constructor taking a `std::initializer_list`, unlike `std::vector`.

Could it be possible to add this?

This shoud be straightforward to add, using other constructors.

**Comment by miscco** [comment]
@Eren121 thanks for reporting this. I have opened a PR that should alleviate the issue
