### ISSUE TITLE
Documentation behind `#if 0`

### ISSUE THREAD

**Issue by pauleonix** [NVIDIA/thrust#1858]
I find a lot of documentation in the header files that is behind `#if 0`. Often this is combined with comments like

> declare these members for the purpose of Doxygenating them they actually exist in a derived-from class

or

> Doxygen only

I am certain that this documentation is missing from both the old and the new website. 

In addition I have observed that some of these have been changed to `#if THRUST_DOXYGEN` in 3b6f6235afab26142ad7f7f42169caf588f60779 causing them to appear on the websites.

Is all this documentation missing by accident or is it deemed outdated and therefore absent until updated/reviewed?

Instances can easily be found by greping for `#if 0`. The example that caused me to get into this was https://github.com/NVIDIA/thrust/blob/3cfb481725a8fa46e87d5f1b80dd4ae2931539e2/thrust/device_reference.h#L309 hiding a lot of the member functions that `device_reference` inherits from its parent class.

**Comment by miscco** [comment]
AFAIK this is necessary so that doxygen sees behind C++ inheritance 

Closing this as there is nothing to fix here

**Comment by pauleonix** [comment]
@miscco If it were `#if THRUST_DOXYGEN` everywhere, then yes, but Doxygen clearly does **not** see the code behind the `#if 0`, else there would be documentation online about these inherited functions. You may have miss-read my original post?

**Comment by pauleonix** [comment]
@jrhemstad I still think this should be reopened and maybe added to https://github.com/NVIDIA/cccl/issues/51.
