### ISSUE TITLE
Misuse of device_vector's copy constructor results in unhelpful error message	

### ISSUE THREAD

**Issue by jaredhoberock** [NVIDIA/thrust#37]
The copy constructor of a device vector with different types does not work:

```
thrust::device_vector<float> t1(10);
thrust::device_vector<double> t2(t1);
```

It does work for host vectors. I am using Thrust version from CUDA 4.0. Thanks for a great library.

Forwarded from http://code.google.com/p/thrust/issues/detail?id=409

**Comment by allisonvacanti** [comment]
The code above currently compiles and works as expected.
