### ISSUE TITLE
Make fallback_allocator example use the allocator in the device_vector	

### ISSUE THREAD

**Issue by jaredhoberock** [NVIDIA/thrust#40]
Should use thrust::allocator (when it exists) to implement fallback_allocator

Hard to do now without making fallback_allocator verbose. In particular, fallback_allocator should return a tagged pointer instead of a raw pointer

Forwarded from http://code.google.com/p/thrust/issues/detail?id=457

**Comment by allisonvacanti** [comment]
`fallback_allocator` no longer exists.
