### ISSUE TITLE
Enable custom allocation for kernel parameters marshalled through gmem

### ISSUE THREAD

**Issue by jaredhoberock** [NVIDIA/thrust#433]
Reported here: https://groups.google.com/d/msg/thrust-users/-W70r0_B45o/LmdsRGcPb5cJ

Either pass the `execution_policy` to `launch_closure` or allow `bulk::async` to receive an allocator.

**Comment by jrhemstad** [comment]
The link is no longer accessible and so this issue is no longer actionable.
