### ISSUE TITLE
Implement N3421 - Making Operator Functors greater<>

### ISSUE THREAD

**Issue by gnzlbg** [NVIDIA/thrust#468]
Summarizing [N3421](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2012/n3421.htm), apply following changes to function objects in `<thrust/functional.h>`:

Change

``` c++
template <class T> struct plus;
```

to

``` c++
template <class T = void> struct plus;
template <> struct plus<void>;
```

That is, add `= void` default template arguments, and `<void>` explicit
specializations, which are defined as:

``` c++
/// In C++03
template <> struct plus<void> {
  template <class T> 
  __host__ __device__
  T operator()(T const& lhs, T const& rhs) const { return lhs + rhs; };
};

/// Future possible migration to C++11/1y
template <> struct plus<void> {
  template <class T, class U>
  __host__ __device__
  auto operator()(T&& t, U&& u) const 
  THRUST_RETURNS__(std::forward<T>(t) + std::forward<U>(u));
};
```

Remarks:
- Draft [N3421](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2012/n3421.htm) is accepted for C++14, and thus suggests only the C++14 version.
- The suggested C++03 version provides the same functionality as the current thrust version but with nicer syntax: `sort(vec.begin(), vec.end(), greater<>())`.
- The suggested C++03 version can be easily extended to the C++14 version in the future. 
- The C++14 version supports extra functionality: e.g. adding elements of two different types and choosing the correct return type via decltype.
- `THRUST_RETURNS__` is a macro that does `noexcept(expr) -> decltype(expr) { return expr; }`. This is still necessary in C++14 since _automatic return type deduction for normal functions_ does not choose the correct noexcept qualifier and does not allow for expression SFIANE on the return type. Dave Abrahams showed it [here](https://groups.google.com/forum/#!msg/boost-devel-archive/OzJ5Ft3pSnU/b_Ter9bgNqAJ).

**Comment by jrhemstad** [comment]
This looks to be done as of https://github.com/NVIDIA/thrust/commit/b5284512e83bf91eac9010ef370ce27988ae091f
