### ISSUE TITLE
Asynchronous Algorithm Interface

### ISSUE THREAD

**Issue by jaredhoberock** [NVIDIA/thrust#500]
We need a portable way to execute algorithms asynchronously. The obvious way to do this is to utilize `future`s.

An asynchronous reduction could look like this:

```
template<typename ExecutionPolicy, typename FutureOrIterator, typename FutureOrIterator, typename FutureOrT, typename FutureOrBinaryOp>
future<T> async_reduce(ExecutionPolicy&& exec, FutureOrIterator first, FutureOrIterator last, FutureOrT init, FutureOrBinaryOp binary_op);
```

This interface can accept `future`s or values, but maybe it should only accept `future`s and make it the caller's responsibility to pass something marshaled through something like `make_ready_future`.

Blocked by: Promises & Futures #126

**Comment by jrhemstad** [comment]
We've since added `thrust::async` algorithms, but have also since deprecated them.

Our current plant for composing asynchronous algorithms is via P2300/[stdexec](https://github.com/NVIDIA/stdexec)
