### ISSUE TITLE
CUDA's fill implementation is too complicated

### ISSUE THREAD

**Issue by jaredhoberock** [NVIDIA/thrust#505]
The complex implementation exists mainly to improve performance on sm_10. We don't even support sm_1x anymore, so we should investigate whether eliminating `fill`'s specialization yields any significant performance improvement.

**Comment by elstehle** [comment]
It looks like `fill` has been refactored as part of [this commit](https://github.com/NVIDIA/thrust/commit/3b6b107b940bc32e0c5701200f2347d6a03975ba#diff-3f3f724cb4bc39f4a355e936e2a8d0e69dd70b3d5f36a40f6ecda5ae37c66deb). It seems the issue has been resolved in the meanwhile.
