### ISSUE TITLE
remove manual unrolling in cuda::block::inclusive_scan

### ISSUE THREAD

**Issue by jaredhoberock** [NVIDIA/thrust#53]
The statically-sized variants could be implemented with TMP or automatic compiler-based unrolling (w/ #pragma unroll).  The latter would likely require use of a static log2<N>.

Forwarded from http://code.google.com/p/thrust/issues/detail?id=407

**Comment by allisonvacanti** [comment]
Closing, `cuda::block` is not present in current Thrust.
