### ISSUE TITLE
CUDA implementation of thrust::reduce_by_key outputs last equivalent key instead of first

### ISSUE THREAD

**Issue by jaredhoberock** [NVIDIA/thrust#550]
Seems to have been broken like this for a while.

**Comment by brycelelbach** [comment]
Do you happen to have a test case for this?

If not, no problem, it'll be easy to write.

**Comment by jaredhoberock** [comment]
Not anymore, sorry, but I think it should straightforward to produce a program that reveals the inconsistency.

**Comment by miscco** [comment]
Closing this as I assume this to be resolved
