### ISSUE TITLE
Algorithms which copy values between host & device should use the supplied-stream

### ISSUE THREAD

**Issue by jaredhoberock** [NVIDIA/thrust#560]
Algorithms like `reduce` return values to the caller by dereferencing an iterator. This is implemented with a call to `cudaMemcpyAsync(..., 0)`. Since stream 0 is used (even if the user supplies a stream via execution policy), this causes global synchronization.

We ought to try to get the user's stream into this call, and also have the calling thread synchronize with it after the copy.

**Comment by miscco** [comment]
Closing this as resolved
