### ISSUE TITLE
unified memory allocator and pointer classes?

### ISSUE THREAD

**Issue by rnburn** [NVIDIA/thrust#569]
Could you add an allocator class that uses cudaMallocManaged? This would be very useful for those implementing custom container classes.

I would image it as having a distinct pointer object (e.g. ManagedPtr) that doesn't default to either host or device execution policy but is implicitly convertible to either a built-in pointer for host execution, some sort of ManagedDevicePtr object that indicates device execution, or could be used by explicitly supplying an execution policy to the thrust algorithm functions.

Also, MangedPtr could be made to fulfill all of the requirements for a RandomAccessIterator (including having an iterator_category that's convertible to random_access_iterator_tag) so that it could be used with STL algorithm functions as well.

**Comment by brycelelbach** [comment]
Doesn't device_allocator do this?

**Comment by jaredhoberock** [comment]
`device_allocator` uses `cudaMalloc` and allocates fancy `device_ptr`s.

A hypothetical `managed_allocator` [1,2] which used `cudaMallocManaged` might work differently.

[1] https://github.com/jaredhoberock/managed_allocator

[2] https://github.com/agency-library/agency/blob/master/agency/cuda/memory/allocator/managed_allocator.hpp

**Comment by brycelelbach** [comment]
Ah, yes, I misunderstood.

Yes, this is on my todo list :).

**Comment by sbudenkov** [comment]
Hi,
Is it still in the backlog?

**Comment by senior-zero** [comment]
Hello @sbudenkov! The following [PR](https://github.com/NVIDIA/thrust/pull/1334) seems to have added `universal_allocator`.
