### ISSUE TITLE
add string sorting example

### ISSUE THREAD

**Issue by jaredhoberock** [NVIDIA/thrust#57]
The earlier article is no longer available [1], so we should provide an example ourselves.

[1] http://www.linuxfoundation.org/news-media/ldn/2009/10/c-gpu-and-thrust-strings-gpu

Forwarded from http://code.google.com/p/thrust/issues/detail?id=448

**Comment by jrhemstad** [comment]
While I think a string sorting example would be interesting, neither of the original links are still valid. Closing this as not actionable.
