### ISSUE TITLE
consider removing device-to-device copy workaround for absence of nvcc

### ISSUE THREAD

**Issue by jaredhoberock** [NVIDIA/thrust#58]
IIRC we decided to eliminate this WAR because it violates the one-definition rule and there's no way to ensure we get the "good" version when both are present.

[1] http://code.google.com/p/thrust/source/browse/thrust/system/cuda/detail/copy_device_to_device.inl#41

I don't think we should modify that code unless we get a bug report

I'll take a look at this later.  I can't say what the right approach is, but I'm concerned about the silent (and hard to diagnose) performance hazard that this introduces.

Forwarded from http://code.google.com/p/thrust/issues/detail?id=449

**Comment by allisonvacanti** [comment]
The `copy_device_to_device` implementation was rewritten in 2016.
