### ISSUE TITLE
Consolidate and improve the testing infrastructure

### ISSUE THREAD

**Issue by jaredhoberock** [NVIDIA/thrust#591]
The unit testing infrastructure should report more details about the system which compiled & executed the test. It would make it easier to reproduce failures if additional info was available, e.g., compiler version details.

**Comment by brycelelbach** [comment]
We have 4-5 testing drivers now, sadly. I'm hoping to consolidate them.

**Comment by jrhemstad** [comment]
We've standardized on Catch2 in CUB and will transition to using it in Thrust. 

https://github.com/NVIDIA/cub/pull/365
