### ISSUE TITLE
Consider reductions which respect noncommutativity of binary operation

### ISSUE THREAD

**Issue by jaredhoberock** [NVIDIA/thrust#596]
Could add `thrust::accumulate` and `thrust::accumulate_by_key`. Would be useful in implementing the scan algorithms.

**Comment by cwharris** [comment]
This algorithm seems to be implemented per-kernel in various places in RAPIDS. If thrust provided this algorithm, we could not only consolidate some of that code, but also reduce future development time while hypothetically producing optimally paralleled code. `reduce_by_key` is the right approach if your operation can be made commutative, but that is often not feasible/possible. Some operations are by their nature non-commutative.

Examples
 - cuspatial has non-commutative operations. Hausdorff Distance for multiple pairs of spaces can be implemented in `O(n^2)` time without requiring temp memory (may require `lower_bound` per element). The same operation can be done as two `reduce_by_key`s, but would require `n*m` temp memory (where `n` is the total number of points, and `m` is number of spaces compared).
- natural language processing. the order in which words appear in a sentence is important, and therefore operations relying on the order of those words may be by nature non-commutative.
- cugraph has non-commutative operations (citation needed).
- cuml has non-commutative operations (citation needed).

Perhaps implementing non-commutative operations on a per-case bases does indeed provide optimal results, but those results take significantly more time to develop than using a higher level function which can take a vector and an associative non-commutative operator and scale across device.

I'm interested in working on this, but I have not contributed to Thrust before. Currently, I'm stuck trying to `make -j` (build stalls).

**Comment by cwharris** [comment]
#951

**Comment by jrhemstad** [comment]
Closing in favor of https://github.com/NVIDIA/thrust/issues/1434
