### ISSUE TITLE
remove Thrust 1.6.0 deprecations

### ISSUE THREAD

**Issue by jaredhoberock** [NVIDIA/thrust#60]
these aliases were deprecated in v1.6.0:
- `device_space_tag`
- `host_space_tag`
- `iterator_space`
- `any_space_tag`
- `THRUST_DEVICE_BACKEND`
- `THRUST_HOST_BACKEND`

Forwarded from http://code.google.com/p/thrust/issues/detail?id=466

**Comment by allisonvacanti** [comment]
Looks like the `BACKEND` defined are still present, but the others have been removed. This should be cleaned up for 2.0.
