### ISSUE TITLE
Compile error when using aligned struct with host_vector or device_vector

### ISSUE THREAD

**Issue by froce** [NVIDIA/thrust#625]
Similar to the issue reported and fixed back here:
https://code.google.com/p/thrust/issues/detail?id=44

created by creating a host_vector or device_vector of an aligned type and adding any elements to it:

struct __align__(16) MyVector { float x, y, z, w; }
thrust::host_vector<MyVector> vectors(1);

Errors:
1>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\include\thrust/detail/generate.inl(58): error C2719: 'gen': formal parameter with __declspec(align('16')) won't be aligned
1>          C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\include\thrust/system/detail/generic/fill.h(41) : see reference to function template instantiation 'OutputIterator thrust::generate_n<DerivedPolicy,OutputIterator,Size,thrust::detail::fill_functor<T>>(const thrust::detail::execution_policy_base<DerivedPolicy> &,OutputIterator,Size,Generator)' being compiled
1>          with
1>          [
1>              OutputIterator=MyVector *
1>  ,            DerivedPolicy=thrust::system::cpp::detail::tag
1>  ,            Size=unsigned int
1>  ,            T=MyVector
1>  ,            Generator=thrust::detail::fill_functor<MyVector>
1>          ]
1>          C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\include\thrust/detail/fill.inl(54) : see reference to function template instantiation 'OutputIterator thrust::system::detail::generic::fill_n<Derived,OutputIterator,Size,T>(thrust::execution_policy<Derived> &,OutputIterator,Size,const T &)' being compiled
1>          with
1>          [
1>              OutputIterator=MyVector *
1>  ,            Derived=thrust::system::cpp::detail::tag
1>  ,            Size=unsigned int
1>  ,            T=MyVector
1>          ]
1>          C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\include\thrust/system/detail/generic/uninitialized_fill.inl(74) : see reference to function template instantiation 'OutputIterator thrust::fill_n<DerivedPolicy,ForwardIterator,Size,T>(const thrust::detail::execution_policy_base<DerivedPolicy> &,OutputIterator,Size,const T &)' being compiled
1>          with
1>          [
1>              OutputIterator=MyVector *
1>  ,            DerivedPolicy=thrust::system::cpp::detail::tag
1>  ,            ForwardIterator=MyVector *
1>  ,            Size=unsigned int
1>  ,            T=MyVector
1>          ]
1>          C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\include\thrust/system/detail/generic/uninitialized_fill.inl(126) : see reference to function template instantiation 'ForwardIterator thrust::system::detail::generic::detail::uninitialized_fill_n<Derived,ForwardIterator,Size,T>(thrust::execution_policy<Derived> &,ForwardIterator,Size,const T &,thrust::detail::true_type)' being compiled
1>          with
1>          [
1>              ForwardIterator=MyVector *
1>  ,            Derived=thrust::system::cpp::detail::tag
1>  ,            Size=unsigned int
1>  ,            T=MyVector
1>          ]
1>          C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\include\thrust/detail/uninitialized_fill.inl(54) : see reference to function template instantiation 'ForwardIterator thrust::system::detail::generic::uninitialized_fill_n<Derived,ForwardIterator,Size,T>(thrust::execution_policy<Derived> &,ForwardIterator,Size,const T &)' being compiled
1>          with
1>          [
1>              ForwardIterator=MyVector *
1>  ,            Derived=thrust::system::cpp::detail::tag
1>  ,            Size=unsigned int
1>  ,            T=MyVector
1>          ]
1>          C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\include\thrust/detail/allocator/default_construct_range.inl(94) : see reference to function template instantiation 'ForwardIterator thrust::uninitialized_fill_n<DerivedPolicy,Pointer,Size,MyVector>(const thrust::detail::execution_policy_base<DerivedPolicy> &,ForwardIterator,Size,const T &)' being compiled
1>          with
1>          [
1>              ForwardIterator=MyVector *
1>  ,            DerivedPolicy=thrust::system::cpp::detail::tag
1>  ,            Pointer=MyVector *
1>  ,            Size=unsigned int
1>  ,            T=MyVector
1>          ]
1>          C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\include\thrust/detail/allocator/default_construct_range.inl(105) : see reference to function template instantiation 'void thrust::detail::allocator_traits_detail::default_construct_range<Allocator,Pointer,Size>(Allocator &,Pointer,Size)' being compiled
1>          with
1>          [
1>              Allocator=std::allocator<MyVector>
1>  ,            Pointer=MyVector *
1>  ,            Size=unsigned int
1>          ]
1>          C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\include\thrust/detail/contiguous_storage.inl(194) : see reference to function template instantiation 'void thrust::detail::default_construct_rangestd::allocator<T,Base,unsigned int>(Allocator &,Pointer,Size)' being compiled
1>          with
1>          [
1>              T=MyVector
1>  ,            Base=MyVector *
1>  ,            Allocator=std::allocator<MyVector>
1>  ,            Pointer=MyVector *
1>  ,            Size=unsigned int
1>          ]
1>          C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\include\thrust/detail/contiguous_storage.inl(193) : while compiling class template member function 'void thrust::detail::contiguous_storage<T,Alloc>::default_construct_n(thrust::detail::normal_iterator<MyVector *>,unsigned int)'
1>          with
1>          [
1>              T=MyVector
1>  ,            Alloc=std::allocator<MyVector>
1>          ]
1>          C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\include\thrust/detail/vector_base.inl(151) : see reference to function template instantiation 'void thrust::detail::contiguous_storage<T,Alloc>::default_construct_n(thrust::detail::normal_iterator<MyVector *>,unsigned int)' being compiled
1>          with
1>          [
1>              T=MyVector
1>  ,            Alloc=std::allocator<MyVector>
1>          ]
1>          C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\include\thrust/detail/vector_base.inl(321) : while compiling class template member function 'thrust::detail::normal_iterator<MyVector *> thrust::detail::vector_base<T,Alloc>::begin(void)'
1>          with
1>          [
1>              T=MyVector
1>  ,            Alloc=std::allocator<MyVector>
1>          ]
1>          C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\include\thrust/detail/vector_base.inl(474) : see reference to function template instantiation 'thrust::detail::normal_iterator<MyVector *> thrust::detail::vector_base<T,Alloc>::begin(void)' being compiled
1>          with
1>          [
1>              T=MyVector
1>  ,            Alloc=std::allocator<MyVector>
1>          ]
1>          C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\include\thrust/detail/vector_base.inl(52) : while compiling class template member function 'thrust::detail::vector_base<T,Alloc>::vector_base(unsigned int)'
1>          with
1>          [
1>              T=MyVector
1>  ,            Alloc=std::allocator<MyVector>
1>          ]
1>          C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\include\thrust/host_vector.h(76) : see reference to function template instantiation 'thrust::detail::vector_base<T,Alloc>::vector_base(unsigned int)' being compiled
1>          with
1>          [
1>              T=MyVector
1>  ,            Alloc=std::allocator<MyVector>
1>          ]
1>          C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\include\thrust/host_vector.h(52) : see reference to class template instantiation 'thrust::detail::vector_base<T,Alloc>' being compiled
1>          with
1>          [
1>              T=MyVector
1>  ,            Alloc=std::allocator<MyVector>
1>          ]
1>          D:/Eigene Dokumente/Visual Studio 2013/Projects/memory_alignment_test/memory_alignment_test/kernel.cu(103) : see reference to class template instantiation 'thrust::host_vector<MyVector,std::allocator<T>>' being compiled
1>          with
1>          [
1>              T=MyVector
1>          ]

**Comment by Robadob** [comment]
I just had this affect me using the thrust packaged with CUDA 7.0 also.

**Comment by jrhemstad** [comment]
https://godbolt.org/z/94oGqdMfP This no longer looks to be an issue.
