### ISSUE TITLE
thrust::reduce does not handle large input ranges correctly

### ISSUE THREAD

**Issue by wrf1** [NVIDIA/thrust#655]
Thrust 1.8 treats long long int as if it were long int. Here's a demo program:

```
#include <thrust/reduce.h>
#include <thrust/iterator/constant_iterator.h>
void tryit(long long int n) {
  // with long long
  long long int s = 
    thrust::reduce(
    thrust::constant_iterator<long long int>(1LL),
    thrust::constant_iterator<long long int>(1LL)+n);
  std::cout << "long long: " << n << ' ' << s 
                 << std::endl;
  // now with long
  long int n1 = n;
  long int s1 = 
   thrust::reduce(thrust::constant_iterator<int>(1),
   thrust::constant_iterator<int>(1)+n1);
  std::cout << "long: " << n1 << ' ' << s1 
                 << std::endl;
}
int main() {
  tryit(1000000);
  tryit(1000000000);
  tryit(10000000000);
}
```

The output is:

```
long long: 1000000 1000000
long: 1000000 1000000
long long: 1000000000 1000000000
long: 1000000000 1000000000
long long: 10000000000 1410065408
long: 10000000000 1410065408
```

The first 1410065408 should be 10000000000.

I compiled it thus:

nvcc -arch=compute_30 -std=c++11 longlongb.cu -o longlongb

My system is:

Linux 3.16.0-31-generic #43~14.04.1-Ubuntu SMP Tue Mar 10 20:13:38 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

This appears to be a bug.  Thanks.

**Comment by brycelelbach** [comment]
This is being tracked by nvbug 1632709 and nvbug 2004711.

This may be partially fixed by a recent refactoring of reduce that I did. The sequential host implementation is still broken. The reduce refactoring was not in CUDA 9.0, but it is in the next release candidate.

**Comment by jrhemstad** [comment]
Duplicate https://github.com/NVIDIA/thrust/issues/1271
