### ISSUE TITLE
Consider operator bool for thrust::pointer

### ISSUE THREAD

**Issue by jaredhoberock** [NVIDIA/thrust#662]
`unique_ptr` & `shared_ptr` both have `explicit operator bool const ()` functions.

Use case mentioned here: http://stackoverflow.com/questions/29536854/cuda-thrust-checking-for-null-pointers

**Comment by sethrj** [comment]
I'm on board with this idea. It is especially nice for OpenACC/CUDA interoperability: `acc_deviceptr` will return a null pointer if the data isn't allocated on the device, and it may be more convenient to check for null *after* converting from the raw pointer.

**Comment by brycelelbach** [comment]
Yah, this should be pretty straightforward to do.

**Comment by jrhemstad** [comment]
This now exists https://github.com/NVIDIA/thrust/blob/6f64b4a86b0ba1f4e8f3da6c4f7cddc2c91e08f4/thrust/detail/pointer.inl#L161-L167
