### ISSUE TITLE
consider using user's provided stream during host <-> device copies

### ISSUE THREAD

**Issue by AdamSimpson** [NVIDIA/thrust#684]
It appears that thrust has issues with CUDA stream usage under certain circumstances. Initially I came across this bug while interoperating with OpenACC and with the help of the Thrust google group now have a reproducer that doesn't require OpenACC: https://groups.google.com/forum/#!topic/thrust-users/4_z3DajPa2o .

The stream make target of the following repo demonstrates the bug: https://github.com/AdamSimpson/thrust_bug . The code creates a cuda stream and then launches two  thrust::copy_if kernels into the stream. The first kernel seems to run as expected but the second kernel produces the incorrect result. Looking at the timeline in NVVP you can see that the second kernel copies it's output iterator result back to the host before it should be doing so. I believe this may be related to the following issue: https://github.com/thrust/thrust/issues/560 . 

Note that this only happens when compiled with the nvcc 7.0+ flag "--default-stream per-thread"(and when interoperating with PGI's OpenACC as shown in the acc make target of the reproducer). I have tested with the default thrust provided with CUDA/7.0, CUDA/7.5, and the latest copy available from git.

**Comment by jaredhoberock** [comment]
Thanks for the report, Adam.

The problem seems to be due at least partially to #685.

**Comment by AdamSimpson** [comment]
Thanks for the quick response, it does appear that https://github.com/thrust/thrust/issues/685 fixes the --default-stream per thread issue. Unfortunately the OpenACC issue still appears to be present.

**Comment by AdamSimpson** [comment]
It appears that PGI creates OpenACC streams using the cudaStreamNonBlocking flag, which causes the created stream to not be synchronous with the default stream. 

I can recreate this issue with just NVCC/Thrust by modifying the stream reproducer provided above to create it's stream with the cudaStreamNonBlocking flag.

**Comment by jaredhoberock** [comment]
Looks like implementing this would require using `get_value()` with the user's execution policy instead of doing iterator dereferences to implement the host <-> copies in algorithms like copy_if et al. `get_value` would need to synchronize somehow after calling `assign_value()`.

**Comment by brycelelbach** [comment]
Is this still an issue? E.g. are we still unable to use non-blocking streams in Thrust?

Streams support was added after the fact to Thrust. We need to come up with a proper asynchronous API (that, presumably, interoperates with streams or is built on top of stream-based futures).

**Comment by miscco** [comment]
I am closing this as resolved. Please reopen if the issue still appears for you
