### ISSUE TITLE
scrub thrust::complex's use of <cfloat> macros

### ISSUE THREAD

**Issue by jaredhoberock** [NVIDIA/thrust#732]
The implementation of `thrust::complex` uses preprocessor macros in `__host__ __device__` functions.

For example, `DBL_EPSILON`, [here](https://github.com/thrust/thrust/blob/master/thrust/detail/complex/catrig.h#L189).

The implementation of the Standard Library need not implement these macros as literals. Instead, it may use a globally-defined variable.

In this case, `nvcc` will complain that a `__host__ __device__` function is attempting to use a global variable, which is illegal.

As a solution, Thrust should avoid using such macros and instead use some other scheme which would be portable to `__host__ __device__` functions.

**Comment by brycelelbach** [comment]
0.) Has this been a problem in the wild?
1.) Any suggestions for what "some other scheme" would be?

**Comment by jaredhoberock** [comment]
I think the issue is that the implementation of `thrust::complex` has proved expensive to maintain due to inconsistencies of implementations of the various things on which it depends. So yes, it has caused tangible problems.

Some other scheme might include not relying on those various dependencies and instead introduce our own independent implementation which would be reliable.

**Comment by FilipeMaia** [comment]
What other dependencies/assumptions are problematic, or is it just the cfloat macros? I guess one could implement those...

**Comment by jaredhoberock** [comment]
It's been awhile, and I'm having trouble recalling all of the issues, but [here are some examples](https://github.com/thrust/thrust/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20complex).

For the purposes of this issue, the original post simply mentions the `<cfloat>` macros used underneath `detail/complex`.

On the other hand, if we can't actually point to any unit tests that are failing, there's no sense in introducing churn.
