### ISSUE TITLE
warnings when using host_vector<host_vector<T>>

### ISSUE THREAD

**Issue by 3gx** [NVIDIA/thrust#741]
Here is repro:

```
$ cat repro.cu
#include <thrust/host_vector.h>

int main(void)
{
  thrust::host_vector<thrust::host_vector<int> > foo;
}
```

**output**

```
$ nvcc repro.cu
/usr/local/cuda/bin/..//include/thrust/detail/contiguous_storage.inl(257): warning: calling a __host__ function("thrust::detail::vector_base<int, std::allocator<int> > ::~vector_base") from a __host__ __device__ function("thrust::detail::vector_base<int, std::allocator<int> > ::~vector_base [subobject]") is not allowed
```

**Comment by egaburov** [comment]
Here is a simpler repro:

    $ cat repro_simple.cu
    #include <thrust/host_vector.h>
    
    struct Foo
    {
      ~Foo() {}
    };
    int main(void)
    {
      thrust::host_vector<Foo> foo;
    }

**output**

    $ nvcc repro_simple.cu  -c
    /usr/local/cuda/bin/..//include/thrust/detail/allocator/destroy_range.inl(126): warning: calling a __host__ function from a __host__ __device__ function is not allowed
              detected during:
                instantiation of "void thrust::detail::allocator_traits_detail::gozer::operator()(T &) [with T=Foo]"
    /usr/local/cuda/bin/..//include/thrust/detail/function.h(51): here
                instantiation of "Result thrust::detail::wrapped_function<Function, Result>::operator()(Argument &) const [with Function=thrust::detail::allocator_traits_detail::gozer, Result=void, Argument=Foo]"
    /usr/local/cuda/bin/..//include/thrust/system/detail/sequential/for_each.h(83): here
                instantiation of "InputIterator thrust::system::detail::seq


Annotating destructor as __host__ __device__ removes the warning.

**Comment by jaredhoberock** [comment]
If I use `__thrust_exec_check_disable__` at the line of interest, the warning is eliminated:

```
$ git diff
diff --git a/thrust/detail/allocator/destroy_range.inl b/thrust/detail/allocator/destroy_range.inl
index 29549bf..d647457 100644
--- a/thrust/detail/allocator/destroy_range.inl
+++ b/thrust/detail/allocator/destroy_range.inl
@@ -119,6 +119,7 @@ __host__ __device__
 // we must prepare for His coming
 struct gozer
 {
+  __thrust_exec_check_disable__
   template<typename T>
   inline __host__ __device__
   void operator()(T &x)
$ nvcc -I. test.cu 
```

I think that's the correct fix for this particular example -- since the `__host__ __device__` functor calls `T`'s destructor, it needs to guard against the case where `~T()` is not annotated.

**Comment by egaburov** [comment]
Correct, but this doesn't fix warnings in the first repro...

**Comment by egaburov** [comment]
What is so special about thrust::host_vector<int> destructor that the warning is not suppressed?

**Comment by egaburov** [comment]
Here is simple repro for which warning supression doesn't work:

    $ cat repro_simple.cu
    #include <thrust/host_vector.h>
    
    struct Bar
    {
      ~Bar();
    };
    struct Foo : Bar
    {
    };
    int main(void)
    {
      thrust::host_vector<Foo> foo;
    }

**output**

    $ nvcc repro_simple.cu  -c -I.
    repro_simple.cu(7) (col. 8): warning: calling a __host__ function("Bar::~Bar [subobject]") from a __host__ __device__ function("Foo::~Foo") is not allowed

**Comment by egaburov** [comment]
Prepending `virtual` to '~Bar()` removes the warning.

**Comment by allisonvacanti** [comment]
This seems to be fixed in the current version: https://www.godbolt.org/z/zGMsfn
