### ISSUE TITLE
device algorithms should not assume the presence of default constructors (when possible)

### ISSUE THREAD

**Issue by jaredhoberock** [NVIDIA/thrust#78]
We should not require types to have default constructors unless the algorithm truly requires them.  Eventually we should test our standard algorithms with user-defined types that do not provide a default constructor.

Forwarded from http://code.google.com/p/thrust/issues/detail?id=167

**Comment by jrhemstad** [comment]
While this is true, we should open issues specific to each algorithm as needed.
