### ISSUE TITLE
min & max need to return references

### ISSUE THREAD

**Issue by jaredhoberock** [NVIDIA/thrust#79]
The current versions return values

We won't want to do this anytime soon since the perf reduction in kernel code is severe.  For example, using the reference version in a max-reduction reduces performance by 75%.

Forwarded from http://code.google.com/p/thrust/issues/detail?id=176

**Comment by jrhemstad** [comment]
This will be tackled when replacing `thrust::min/max` with `cuda::std::min/max`.
