### ISSUE TITLE
Document whether or not `thrust::gather` can be used in-place

### ISSUE THREAD

**Issue by OrangeOwlSolutions** [NVIDIA/thrust#876]
The issue is described in detail at the following StackOverflow post: [Can thrust::gather be used “in-place”?](http://stackoverflow.com/questions/42560237/can-thrustgather-be-used-in-place). We would then request an of the existing restriction in the documentation of thrust::gather against an overlap of output with map, with an additional restriction against the overlap of output with input.
Thanks.

**Comment by brycelelbach** [comment]
I'm sorry, I'm a little unclear on what the requested doc change is. Can you clarify?

**Comment by brycelelbach** [comment]
I think I'm clear on what the change is you want. Tracked internally by NVBug 2062285.

**Comment by jrhemstad** [comment]
This looks to be done https://nvidia.github.io/thrust/api/groups/group__gathering.html#functions

```Preconditions:
The range [map_first, map_last) shall not overlap the range [result, result + (map_last - map_first)).
The input data shall not overlap the range [result, result + (map_last - map_first)).
```
