### ISSUE TITLE
Magic Number 896 in thrust::transform_reduce

### ISSUE THREAD

**Issue by hopingforblessing** [NVIDIA/thrust#896]
Hello,

---------- Preface (you could skip this) -----------
CUDA/Thrust is amazing and it gives a super boost to my code.
I am working an extension of thrust example file monte_carlo_disjoint_sequence.cu or monte_carlo.cu, where thrust::transform_reduce use a unary_function to calculate a single counting value then aggregate the summation.

estimate += thrust::transform_reduce(thrust::counting_iterator<int>(0),
			thrust::counting_iterator<int>(**M**), estimate_pi(), 0.0f, thrust::plus<float>());

---------- !!! Issue !!! -----------
However, a magic number 896 shows up, and this might be a bug... This is found when I ran the code on Nvidia 960M then later confirmed on Tesla K20 and Tesla K40.

**1)** If I do: **M = 1000**, and print the "thread_id" in the __device__ function, then I have a clear count of thread_id from 0 to 998 (each print once) then thread_id = 999 prints out 128 times. 

**2)** If I do **M = 4000**, and print out the "thread_id", what shows up is: from 0 to 1790, 1792 to 2686, 2688 to 3582, 3584 to 3998, each is printed once, and thread_id = **1791, 2687, 3583 and 3999** are printed **32** times.
and 1791 = 896x2 - 1,   2687 = 896x3 -1,   3583 = 896x4 - 1,   3999 = M-1. But 895 is only printed once.

**3)** If I do ** M = 896** or any number less than 896, each thread_id is printed once.
**4)** If I do ** M = 897** or any number greater than 896, the last step is repeatedly printed. 

**So physically, with this issue, you will never get a convergence to accurate pi value.** 
 
---------- My thought (you could skip this) -----------
I assume that _thrust_ dynamically allocate 32 threads to a Stream Multiprocessor (SM).
If M = 896 then there are 28 groups of the 32 threads.
If M = 1000 then there are 32 groups of the 32 threads, plus 4 groups of id = 999.
If M = 4000 then there are 125 groups of the 32 threads, plus 1 group of 1791, 1 group of 2687, 1 group of 3583 and 1 group 3999.

 Happy Thanksgiving Day!

**Comment by brycelelbach** [comment]
Hey,

Thanks for the bug report, sorry in the delay in getting back to you. Unfortunately notifications from this github repo weren't getting emailed to me.

Can you provide a minimal test case to help us reproduce this? Some guidelines for what I need can be found here:

https://github.com/brycelelbach/cpp_bug_reporting_guidelines

**Comment by CNOCycle** [comment]
Hi, @brycelelbach,

According the description from @hopingforblessing, the minimal test case is [monte_carlo.cu](../blob/master/examples/monte_carlo.cu) with the following patch.

```diff
diff --git a/examples/monte_carlo.cu b/examples/monte_carlo.cu
index 4a11c4d..6f232a0 100644
--- a/examples/monte_carlo.cu
+++ b/examples/monte_carlo.cu
@@ -2,10 +2,12 @@
 #include <thrust/iterator/counting_iterator.h>
 #include <thrust/functional.h>
 #include <thrust/transform_reduce.h>
+#include <thrust/execution_policy.h>

 #include <iostream>
 #include <iomanip>
 #include <cmath>
+#include <cstdio>

 // we could vary M & N to find the perf sweet spot

@@ -55,6 +57,8 @@ struct estimate_pi : public thrust::unary_function<unsigned int,float>
     // multiply by 4 to get the area of the whole circle
     sum *= 4.0f;

+    printf("%d\n",thread_id);
+
     // divide by N
     return sum / N;
   }
@@ -63,17 +67,20 @@ struct estimate_pi : public thrust::unary_function<unsigned int,float>
 int main(void)
 {
   // use 30K independent seeds
-  int M = 30000;
+  int M = 1000;

-  float estimate = thrust::transform_reduce(thrust::counting_iterator<int>(0),
+  float estimate = thrust::transform_reduce(thrust::device,
+                                            thrust::counting_iterator<int>(0),
                                             thrust::counting_iterator<int>(M),
                                             estimate_pi(),
                                             0.0f,
                                             thrust::plus<float>());
   estimate /= M;

-  std::cout << std::setprecision(3);
-  std::cout << "pi is approximately " << estimate << std::endl;
+  cudaDeviceSynchronize();
+
+//  std::cout << std::setprecision(3);
+//  std::cout << "pi is approximately " << estimate << std::endl;

   return 0;
 }

```
the compiling and running commands are:
```sh
>>> uname -a
Linux face-test 4.13.0-32-generic #35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
>>>  g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

>>>  nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
>>>  nvcc -arch=sm_35 monte_carlo.cu
>>>  ./a.out | sort -n
[skip]
>>>  ./a.out | grep '998' | wc -l
1
>>> ./a.out | grep '999' | wc -l
128
```

The second test is replacing `thrust::device` with `thrust::host` 
```sh
>>>  nvcc -arch=sm_35 monte_carlo.cu
>>>  ./a.out | sort -n
[skip]
>>>  ./a.out | grep '998' | wc -l
1
>>> ./a.out | grep '999' | wc -l
1 # <- count of 'thread_id = 999 '
```

This issue can not reproduce on my windows 10 computer running CUDA 9.0 with VS2015
```sh
>>> cl.exe
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]

>>> nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:32_Central_Daylight_Time_2017
Cuda compilation tools, release 9.0, V9.0.176

```

**Comment by jrhemstad** [comment]
Sounds like this is fixed in newer versions of Thrust. Feel free to reopen if this is still an issue.
