### ISSUE TITLE
Probable bug in thrust/system/cuda/detail/copy_device_to_device.inl

### ISSUE THREAD

**Issue by ianmccul** [NVIDIA/thrust#903]
In the function copy_device_to_device defined at line 44 of https://github.com/thrust/thrust/blob/master/thrust/system/cuda/detail/copy_device_to_device.inl there is a call

// copy temp2 to device
	    result = thrust::system::cuda::detail::copy_cross_system(temp2.begin(), temp2.end(), result);

But there apparently isn't a 3-parameter version of thrust::system::cuda::detail::copy_cross_system().  All of the overloads of copy_cross_system() defined in thrust/system/cuda/detail/copy_cross_system.h require the first parameter to be a "cross_system<System1,System2> systems".

This causes a compile error when copying from a permitation_iterator to a device_vector.

**Comment by brycelelbach** [comment]
This looks like a pre-CUB refactoring issue; it should not longer be a problem because the CUDA backend has been completely rewritten. Can you try with the version of Thrust in CUDA 9.0 or 9.1?

This should be fixed soon in Github when we get the newer releases of Thrust pushed here.
