### ISSUE TITLE
Last release since 2015

### ISSUE THREAD

**Issue by JaouadROS** [NVIDIA/thrust#907]
I'm discovering `Thrust` library for the first time and I noticed that it hasn't been updated since 2015. I just want to know what is the future of the library and why there haven't been any new release since three years?

**Comment by henryiii** [comment]
See the excellent discussion in #888.

TLDR: Official NVIDIA development and Github diverged, and is now being merged and fixed.

**Comment by JaouadROS** [comment]
@henryiii good news.. the news are interesting and they answer exactly my questions.. Thanks!
