### ISSUE TITLE
thrust::fill does not respect const_iterators

### ISSUE THREAD

**Issue by elalish** [NVIDIA/thrust#908]
If I try the following, I get a compiler error, as expected:
`std::vector<int> test(10);`
`std::fill(test.cbegin(), test.cend(), 1);`
If, on the other hand, I try the equivalent with thrust, I get no error and the code runs:
`thrust::host_vector<int> test(10);`
`thrust::fill(test.cbegin(), test.cend(), 1);`
I shouldn't be allowed to change the values pointed to by const_iterators, correct? I'm using whatever version of thrust ships with Cuda 8. If the behavior is different in a newer version, please let me know!

**Comment by elalish** [comment]
Okay, after reading your reporting guidelines, I'll try to do this a little better:

/* This content is C++ source code (reproduces as either a `.cu` or `.cpp` file).

=========
TEST CASE
=========

thrust::fill will modify the contents of both host and device vectors even when passed const_iterators via cbegin and cend methods. However, thrust::transform correctly complains, so at least this problem is not completely widespread. However, I'm not going to test every function for you; hopefully you have unit tests for that.
*/

#include <thrust/host_vector.h>
#include <thrust/fill.h>

int main(int argc, char** argv) {
  thrust::host_vector<int> test1(10);
  thrust::fill(test1.cbegin(), test1.cend(), 1);
}

/*
==================
STEPS TO REPRODUCE
==================

Compile this program using either nvcc (as a .cu) or g++ (as a .cpp).

===============
EXPECTED OUTPUT
===============

Program fails to compile, complaining about not being able to modify the contents of a const_iterator.

===============
OBSERVED OUTPUT
===============

Program compiles, runs and modifies the unmodifiable content.

===========
ENVIRONMENT
===========

This bug can be reproduced on:

  CUDA Toolkit:         At least 8.0
  Host Compiler:        NVCC and GCC

My local environment:

If you really want such a detailed list, can you give us a script or something to hunt down all these version numbers? Since I highly doubt my system has anything to do with it, here are the basics: 

OS: Ubuntu 16.04
GPU: GeForce 1080

*/

**Comment by brycelelbach** [comment]
Checking it out.

**Comment by brycelelbach** [comment]
Confirmed.

**Comment by brycelelbach** [comment]
Filed internally as NVBug 2089386.

**Comment by brycelelbach** [comment]
Sorry, this got pushed back a bit. Still on my radar, though.

**Comment by brycelelbach** [comment]
This will be fixed soon and available on Github.
