### ISSUE TITLE
Example bounding_box.cu compiles with CUDA 8.0 but not with CUDA 9.1

### ISSUE THREAD

**Issue by OrangeOwlSolutions** [NVIDIA/thrust#909]
The example in object appears at https://github.com/thrust/thrust/blob/master/examples/bounding_box.cu

**Comment by brycelelbach** [comment]
Hi, thanks for your bug report. Unfortunately it is not actionable. Please take a look at [these guidelines](https://github.com/brycelelbach/cpp_bug_reporting_guidelines) and update the bug report.

We have continuous integration for the examples; this one builds for me and for the test system.
