### ISSUE TITLE
add a float16_t data type for half-float support

### ISSUE THREAD

**Issue by jaredhoberock** [NVIDIA/thrust#91]
The half-float [1] type would interoperate with standard 32-bit and 64-bit floats.  Also, to avoid redundant conversions the arithmetic operators should yield a float32_t result.  This behavior is consistent with the use of half-floats as a compressed storage format.

This enhancement would likely depend on  issue #216 .

class float16_t
{
  unsigned short s;

  public:

  // constructors
  **host** **device**
  float16_t()
    : s(float32_t()) {}

  **host** **device**
  float16_t(const float32_t& f)
    : s(__float2half_rn(f)) {}

  // arithmetic
  **host** **device**
  float32_t operator+(const float16_t& f) const
  {
    // note: return a float
    return static_cast<float32_t>(*this) + static_cast<float32_t>(f);
  }

  // cast to float
  **host** **device**
  operator float32_t(void) const
  {
    return __half2float(s);
  }
};

[1] http://en.wikipedia.org/wiki/Half_precision_floating-point_format

Forwarded from http://code.google.com/p/thrust/issues/detail?id=259

**Comment by marcinz** [comment]
Just a note, I was looking for `complex<__half>` support today. I guess this would be a logical continuation of adding `float16_t`.

**Comment by jrhemstad** [comment]
We will be adding extended floating point types to libcu++ in the near future. https://github.com/NVIDIA/libcudacxx/issues/382
