### ISSUE TITLE
Require C++11

### ISSUE THREAD

**Issue by brycelelbach** [NVIDIA/thrust#917]
Let's drop C++03 and require C++11 in Thrust.

Why?
* C++03 is a large maintenance burden (consider our in-house type traits, metaprogramming facilities, tuple, and kernel launch mechanism).
* Continuing to support C++03 slows the velocity of feature development, because we are often obligated to implement compatibility and emulation layers.
* Continuing to support C++03 will segment the codebase, because some new feature will be C++11 only while others will implement compatibility and emulation layers.
* Our C++03 compatibility and emulation layers are a significant source of compile time performance problems (consider our tuple and kernel launch mechanism).
* It's 2018

Furthermore, let's plan for a roadmap going forward.

* In 2020, we will require C++14.
* In 2022, we will require C++17.
* In 2025, we will require C++20.

**Action Items:**
* [ ] **Deprecate C++03 (soon).**
* [ ] **Replace C++03 compatibility and emulation layers with C++11.**
* [ ] **C++ify the codebase.**

**Comment by brycelelbach** [comment]
@jaredhoberock please review and sign off.

**Comment by henryiii** [comment]
This sounds great. I for one would be fully for a C++11 only Thrust.

**Comment by jaredhoberock** [comment]
> Deprecate C++03 (soon).

I think taking this action needs some data indicating that it won't create problems for existing users.

If there is a large portion of the userbase which does not currently have access to a C++11 compiler, I don't think we can actually deprecate C++03. We should do our due diligence and try to find out.

Beyond that line item, I'm fine with requiring C++11 for any new features.

**Comment by henryiii** [comment]
I would think that someone stuck with pre-C++11 compilers (at least before GCC 4.8/Clang 3.5) could also use an older version of Thrust. Dropping C++03 can tremendously simplify a codebase, and spur new development. Just my two cents.

**Comment by jrhemstad** [comment]
C++11 is [already deprecated](https://github.com/NVIDIA/thrust/issues/1059) and C++14 is soon to follow. Both will be removed in the next major release.
