### ISSUE TITLE
Why not add bitonic sort algorithm instead of present sort algorithm  ?  

### ISSUE THREAD

**Issue by 404517981** [NVIDIA/thrust#925]
You can check this Link，https://zhuanlan.zhihu.com/p/40295393 It‘s powerful for array under 2048 size，
because of shared memory.I think the  it can be apply on big  array!

**Comment by brycelelbach** [comment]
We currently use a radix sort for large arrays and a merge sort for smaller arrays.

Is there a particular reason for this request? Are you encountering a performance problem with Thrust's sorting algorithm? Can you provide a minimal working example that reproduces the issue?

**Comment by 404517981** [comment]
https://gitee.com/EASIZM/RenderPro/tree/master

**Comment by brycelelbach** [comment]
I'm sorry, I don't speak whatever that language is.

**Comment by brycelelbach** [comment]
@jaredhoberock can you help evaluate this?

**Comment by 404517981** [comment]
github.com/404517981/Egamer
Use this link download two file named hlslsort and cudasort individual.

**Comment by 404517981** [comment]
github.com/404517981/Egamer
Use this link download two file named hlslsort and cudasort individual.

**Comment by 404517981** [comment]
github.com/404517981/Egamer
Use this link download two file named hlslsort and cudasort individual.

**Comment by 404517981** [comment]
The hlsl sample  runed my GTX1060 is better than thrust, But i'm not sure and need yours confirm.

**Comment by jrhemstad** [comment]
I'm going to close this as the implementation has changed significantly over the years. Please feel free to open another issue if you've tried out the latest version of `thrust::sort` and you still have questions about the performance.
