### ISSUE TITLE
NVBug 2365533: copy_if produces corrupted values for large value types

### ISSUE THREAD

**Issue by robertmaynard** [NVIDIA/thrust#929]
For vectors with value type that has size >=128 bytes copy_if under cuda produces corrupted results.

Originally found in the VTK-m project: https://gitlab.kitware.com/vtk/vtk-m/issues/295

Here is a standalone reproduction of the bug:
https://gitlab.kitware.com/vtk/vtk-m/uploads/44093c0f734530de37cbc79ca455772f/CopyIf.cu

**Comment by elstehle** [comment]
Thanks for opening the issue, @robertmaynard. It seems that this issue has been fixed in the meanwhile:
https://godbolt.org/z/d1oTq1fYT
