### ISSUE TITLE
consider other external references for documentation of algorithms/concepts	

### ISSUE THREAD

**Issue by jaredhoberock** [NVIDIA/thrust#93]
This wiki [1] seems decent, though the documentation of iterator concepts [2] is somewhat lacking vs. the SGI docs.

[1] http://en.cppreference.com/w/cpp/algorithm
[2] http://en.cppreference.com/w/cpp/iterator/concepts

Forwarded from http://code.google.com/p/thrust/issues/detail?id=426

**Comment by brycelelbach** [comment]
In hindsight, this is amusing, given how popular cppreference has become.
