### ISSUE TITLE
No Continous Integration?

### ISSUE THREAD

**Issue by dawagner** [NVIDIA/thrust#943]
When submitting a PR to this project, it would be nice to know whether some test suite successfully builds and runs in a reference environment. A lot of github projects use Travis CI, for instance.

**Comment by griwes** [comment]
This will be coming, in one form or another, in the coming months.

**Comment by dawagner** [comment]
While it is true that Travis CI (and other similar tools) would not be suited to check that the code runs well on specific hardware backends, it would be very useful to make sure that at least the examples compile and that non-GPU tests run fine and with the expected results.

Are you interested in a PR introducing smoke tests on Travis CI?

**Comment by miscco** [comment]
We do have plans to improve our testing infrastructure.

Thanks for bringing this up, but I will close this in favor of more specialized issues in the near future
