### ISSUE TITLE
Feature Request: Provide mechanism to convert thrust::device/host_vector to std::vector

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/thrust#953]
If I have a `thrust::device_vector` or `thrust::host_vector`, I would like to have a convenient way to get a `std::vector` that holds a copy of the `thrust` vector.

Obviously there's no way to provide a `std::vector::operator=` overload.

However, one possibility is to add a implicit conversion operator from a `thrust` vector to a `std::vector`, e.g.,
```
operator std::vector<T>(...)
```

This conversion operator would take care of the necessary allocations and copying of the `thrust` vector's contents. 

Another less appealing option would be a `.to_std_vector()` or similar member function that returns a `std::vector` copy of the `thrust` vector. There could be an overload of `.to_std_vector(std::vector<t> &)` that allows passing in a reference to an existing vector such that you could reuse it's allocation instead of always having to do a new allocation.

**Comment by valleymouth** [comment]
How about constructing them using iterators?
host_vector (InputIterator first, InputIterator last);

**Comment by jaredhoberock** [comment]
For what it's worth, `thrust::complex` includes a conversion to `std::complex` operator.

**Comment by jrhemstad** [comment]
> How about constructing them using iterators?
> host_vector (InputIterator first, InputIterator last);

So I suppose this is a pretty good solution for converting a `thrust::host_vector` to a `std::vector`.

It can also be used for converting a `thrust::device_vector` to `std::vector` using `thrust::host_vector` as an intermediary, but this is a rather unsatisfactory solution:
```
thrust::device_vector<float> d_v(N);
thrust::host_vector<float> h_v(d_v);
std::vector<float> v(h_v.begin(), h_v.end());
```
That looks to me like it would require 2 allocations and 2 copies, plus it's a two-liner when it really could be a one-liner.

**Comment by valleymouth** [comment]
Well, for device_vector you would need to rely on thrust::copy I guess...

**Comment by valleymouth** [comment]
@jaredhoberock That is what makes a device_vector<thrust::complex> constructed from a std::vector<std::complex> using iterators work right... I am just pointing out that there are already ways of achieving what Jacob wants in the current interface.

**Comment by jrhemstad** [comment]
> I am just pointing out that there are already ways of achieving what Jacob wants in the current interface.

Oh I'm well aware there's plenty of ways I can already do this. Typically I just use `cudaMemcpy` directly. My ask is for a more _convenient_ way :)

**Comment by luiset83** [comment]
I think not all of us are aware that there are plenty of ways to do this... at least not without searching for a while and coming up with a few solutions. ;) I was trying to do what @valleymouth suggested, but couldn't get it to compile.

In my case, I was having some additional difficulty given I also have to transfer from thrust::complex<float> to std::complex<float>

One case is going from thrust::device_vector<thrust::complex<float>> back to std::vector<std::complex<float>>:

```
thrust::device_vector<thrust::complex<float>> d_x(M); // initial vector
// transform thrust::device_vector back to std::vector for sending to function
thrust::host_vector<thrust::complex<float>> h_x = d_x;
std::vector<std::complex<float>> ht_s(M);

std::copy(h_x.begin(), h_x.end(), ht_s.begin()); // method 1: works, no warnings

thrust::copy(h_x.begin(), h_x.end(), ht_s.begin()); // method 2: works, generates below warning in debug mode on MSVC2015 and 2017 (no warning for release build)
```

// CUDA\v10.0\include\thrust / detail / allocator / allocator_traits.inl(230) : warning : calling a __host__ function("std::_Iterator_base12::_Iterator_base12") from a __host__ __device__ function("std::_Iterator_base12::_Iterator_base12 [subobject]") is not allowed

I was also trying the opposite, going from std::vector<std::complex<float>> to thrust::device_vector<thrust::complex<float>>, and also got some warnings and compile errors.

Since it seems like some of you already know good/correct ways to do these, could you kindly share with an example? :)

**Comment by valleymouth** [comment]
This compile compiles fine for me on Ubuntu 18.04.2 LTS / cuda 9.1 / gcc-6
Haven't tried with cuda10 + MSVS though... :(

#include <thrust/complex.h>
#include <thrust/device_vector.h>
#include <thrust/host_vector.h>

#include <complex>
#include <vector>

int main(int argc, char** argv)
{
  thrust::device_vector<thrust::complex<float>> d_x(10); // initial vector

  thrust::host_vector<thrust::complex<float>> h_x = d_x;
  std::vector<std::complex<float>> ht_s(10);
  
  std::copy(h_x.begin(), h_x.end(), ht_s.begin()); // method 1: works, no warnings
  
  thrust::copy(h_x.begin(), h_x.end(), ht_s.begin()); // method 2: works, generates below warning in debug mode on MSVC2015 and 2017 (no warning for release build)

  thrust::copy(ht_s.begin(), ht_s.end(), h_x.begin());
  
  return 0;
}

**Comment by luiset83** [comment]
Taking advantage of the constructor mentioned by @jaredhoberock, this seems to work for the host -> device direction for a 'one liner':

```
std::vector<std::complex<float>> s(10);
// cast input vector as thrust::complex<float> from std::complex<float>
thrust::device_vector<thrust::complex<float>> d_s( (thrust::host_vector<thrust::complex<float>>) s );
```

As @jrhemstad commented, I can't think how to make the reverse operation work without 2 allocations and 2 copies. Is it possible to avoid the extra copy/allocation from these types? If so, how?

**Comment by miscco** [comment]
Assignment from std::vector has been implemented, so closing this
