### ISSUE TITLE
How copy function works in mixed data types

### ISSUE THREAD

**Issue by poornamaddu** [NVIDIA/thrust#960]
I am new to to cuda and thrust functionality and I need some information on copy function.When I am copying  data  from host_vector of int data type  to device_vector  of float data type, It uses  the zip_iterator and identity function with in  the for_each_kernel. Identity function taking the zip_iterator and returns the same in the statement f (*first).  But  I  want to understand how and where  the assignment  operation is happening to copy the values in the device_vector.
Here is the sample snip-it code 
int main()
{
  thrust::host_vector<int> v(5);
  v[0] = 0; v[1] = 1; v[2] = 2; v[3] = 3; v[4] = 4;
  thrust::device_vector<float> d(5, (float) 10.5);
  thrust::copy(v.begin(), v.end(), d.begin());

 return 0;
}
Please help me to understand the identity, zip_iterator and for_each_kernel() functionality.
Thank you in advance.

**Comment by miscco** [comment]
That depends on the type and the provided operators. If there is an assignment from T1 to T2 then that is used. Otherwise if there is only a conversion from T1 to T2 then T1 is implicitly converted to T2 and the copy assignment is called.
