### ISSUE TITLE
warning : __declspec attributes ignored in async algorithms

### ISSUE THREAD

**Issue by zhihaoy** [NVIDIA/thrust#975]
I receive the following warning:

```
  C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include\thrust/detail/execute_with_dependencies.h(193): warning : __declspec attributes ignored
```

After including `<thrust/async/copy.h>` in MSVC.  I turned on `/Zc:__cplusplus` in order to include it.

**Comment by allisonvacanti** [comment]
The async algorithms have been updated to work on MSVC 2019. Are you still seeing this issue with the latest version of Thrust?

**Comment by miscco** [comment]
Closing this as async has been deprecated
