### ISSUE TITLE
&*begin doesn't work for empty range

### ISSUE THREAD

**Issue by zhihaoy** [NVIDIA/thrust#983]
This line

https://github.com/thrust/thrust/blob/master/thrust/system/cuda/detail/internal/copy_cross_system.h#L105

causes MSVC to fail in debug build:

![image](https://user-images.githubusercontent.com/43971430/57260944-6b714200-702b-11e9-9daf-2bc647adefa3.png)

which is the motivation for http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4183.pdf

Minimal reproduce: `thrust::copy(device_vec.begin(), device_vec.end(), std_vec.begin());` all empty.

**Comment by miscco** [comment]
I believe this has been fixed since then. Please reopen if it is still happening
