### ISSUE TITLE
On FreeBSD tests print "MSVC_COMPILER_FLAGS:"

### ISSUE THREAD

**Issue by yurivict** [NVIDIA/thrust#988]
```
-- Thrust version 1.9.5
MSVC_COMPILER_FLAGS:
 | WARN_ALL : '/Wall'
 | WARNINGS_AS_ERRORS : '/Wx'
 | RELEASE : '/Ox'
 | DEBUG : '/Zi;-D_DEBUG;/MTd'
 | EXCEPTION_HANDLING : '/EHsc'
 | CPP : ''
 | OMP : '/openmp'
 | TBB : ''
 | CUDA : ''
 | CUDA_BULK : ''
 | WORKAROUNDS : '/DNOMINMAX;/wd4503'
 | C++03 : ''
 | C++11 : '-std=c++11'
```

**Comment by griwes** [comment]
Yeah, we know; this iteration of CMake in Thrust is going away (hopefully by the next full CUDA release). Hope you don't mind me closing this one? (What is currently on `master` will, barring time, land in the next full CUDA release, with improvements in the form of an `install` target and proper CMake package support.)

**Comment by miscco** [comment]
I am closing this as fixed
